### ISSUE TITLE
PlayerVaults creating uuidvaults .yml file for every single user.

### ISSUE THREAD

**Issue by mibby** [drtshock/PlayerVaults#107]
@drtshock 
Using PlayerVaults dev 183.

PlayerVaults is creating a uuid .yml file for every single user who connects to the server. Shouldn't a uuidvaults .yml file only be created when a user actually tries to access a vault (if they have permission to open one) and tries to store something in it? I have over 10,000 .yml files in the folder with 90% of them being empty/blank because those users don't have access to use a vault. I find it to be a bit redundant.

If you could stop blank .yml files from being created for every single user and perhaps add a cleanup command to remove 0kb files, that would be great.

**Comment by drtshock** [comment]
Hm, good point. Will look into this.

**Comment by mibby** [comment]
@drtshock Any update to this issue?

**Comment by mibby** [comment]
Bump.

**Comment by kashike** [comment]
Caused by https://github.com/drtshock/PlayerVaults/commit/bcf9aacd3bdcada594d20724a34ddd53294d12d5

**Comment by mibby** [comment]
@drtshock Any update to this issue? :P

**Comment by mibby** [comment]
Sigh. Guess development has stagnated.  =/

**Comment by drtshock** [comment]
rip

**Comment by mibby** [comment]
RIP indeed. :( Still would love a quick fix to avoid the thousands of empty yml files for users who don't have permission to use/have a vault.

**Comment by kashike** [comment]
@mibby

**Comment by mibby** [comment]
:D Thanks! Worth the wait.

**Comment by mibby** [comment]
@kashike Using the newest dev build with the new commit.
```
[04:36:16] [Server thread/INFO]: mibby issued server command: /chest 1
[04:36:16] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'chest' in plugin PlayerVaults v3.5.7-b188
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched.jar:git-PaperSpigot-b1492af-unknown]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:143) ~[patched.jar:git-PaperSpigot-b1492af-unknown]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) ~[patched.jar:git-PaperSpigot-b1492af-unknown]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189) [patched.jar:git-PaperSpigot-b1492af-unknown]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001) [patched.jar:git-PaperSpigot-b1492af-unknown]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched.jar:git-PaperSpigot-b1492af-unknown]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [patched.jar:git-PaperSpigot-b1492af-unknown]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [patched.jar:git-PaperSpigot-b1492af-unknown]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_74]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_74]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched.jar:git-PaperSpigot-b1492af-unknown]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:773) [patched.jar:git-PaperSpigot-b1492af-unknown]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-PaperSpigot-b1492af-unknown]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-PaperSpigot-b1492af-unknown]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-b1492af-unknown]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
Caused by: java.lang.NullPointerException
	at com.drtshock.playervaults.vaultmanagement.UUIDVaultManager.loadOwnVault(UUIDVaultManager.java:90) ~[?:?]
	at com.drtshock.playervaults.vaultmanagement.VaultOperations.openOwnVault(VaultOperations.java:130) ~[?:?]
	at com.drtshock.playervaults.vaultmanagement.VaultOperations.openOwnVault(VaultOperations.java:155) ~[?:?]
	at com.drtshock.playervaults.commands.VaultCommand.onCommand(VaultCommand.java:35) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched.jar:git-PaperSpigot-b1492af-unknown]
	... 15 more
```

**Comment by kashike** [comment]
@mibby https://github.com/drtshock/PlayerVaults/commit/06bb39d345c1daa5460feea336459e7e06091ebf
