### ISSUE TITLE
Some items are crashing PV and the server

### ISSUE THREAD

**Issue by ManBeastPig** [drtshock/PlayerVaults#147]
I have Magic plugin installed which might be helpful to know.

https://www.spigotmc.org/resources/magic.1056/

Seems like a PV interaction started a fail. It crashes the server but I don't know what item exactly
is causing the crash.

[16:10:41] [Server thread/INFO]: 8833rree issued server command: /pv 1
[16:10:41] [Server thread/ERROR]: Could not call method 'public static org.bukkit.inventory.meta.ItemMeta org.bukkit.craftbukkit.v1_9_R1.inventory.CraftMetaItem$SerializableMeta.deserialize(java.util.Map) throws java.lang.Throwable' of class org.bukkit.craftbukkit.v1_9_R1.inventory.CraftMetaItem$SerializableMeta for deserialization
java.lang.IllegalArgumentException: ItemFlags([HIDE_PLACED_ON, HIDE_UNBREAKABLE, HIDE_POTION_EFFECTS, HIDE_ATTRIBUTES, HIDE_DESTROYS]) is not a valid interface java.util.Set
	at org.bukkit.craftbukkit.v1_9_R1.inventory.CraftMetaItem$SerializableMeta.getObject(CraftMetaItem.java:190) ~[spigot.jar:git-Spigot-bc01c3a-935349e]
	at org.bukkit.craftbukkit.v1_9_R1.inventory.CraftMetaItem.<init>(CraftMetaItem.java:497) ~[spigot.jar:git-Spigot-bc01c3a-935349e]
	at sun.reflect.GeneratedConstructorAccessor150.newInstance(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_72]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_72]
	at org.bukkit.craftbukkit.v1_9_R1.inventory.CraftMetaItem$SerializableMeta.deserialize(CraftMetaItem.java:155) ~[spigot.jar:git-Spigot-bc01c3a-935349e]
	at sun.reflect.GeneratedMethodAccessor318.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:77) [spigot.jar:git-Spigot-bc01c3a-935349e]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:117) [spigot.jar:git-Spigot-bc01c3a-935349e]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:195) [spigot.jar:git-Spigot-bc01c3a-935349e]
	at com.drtshock.playervaults.vaultmanagement.Serialization.deserialize(Serialization.java:152) [PlayerVaults.jar:?]
	at com.drtshock.playervaults.vaultmanagement.Serialization.deserialize(Serialization.java:147) [PlayerVaults.jar:?]
	at com.drtshock.playervaults.vaultmanagement.Serialization.toInventory(Serialization.java:93) [PlayerVaults.jar:?]
	at com.drtshock.playervaults.vaultmanagement.UUIDVaultManager.getInventory(UUIDVaultManager.java:164) [PlayerVaults.jar:?]
	at com.drtshock.playervaults.vaultmanagement.UUIDVaultManager.loadOwnVault(UUIDVaultManager.java:100) [PlayerVaults.jar:?]
	at com.drtshock.playervaults.vaultmanagement.VaultOperations.openOwnVault(VaultOperations.java:130) [PlayerVaults.jar:?]
	at com.drtshock.playervaults.vaultmanagement.VaultOperations.openOwnVault(VaultOperations.java:155) [PlayerVaults.jar:?]
	at com.drtshock.playervaults.commands.VaultCommand.onCommand(VaultCommand.java:34) [PlayerVaults.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot.jar:git-Spigot-bc01c3a-935349e]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-Spigot-bc01c3a-935349e]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) [spigot.jar:git-Spigot-bc01c3a-935349e]
	at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1314) [spigot.jar:git-Spigot-bc01c3a-935349e]
	at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1149) [spigot.jar:git-Spigot-bc01c3a-935349e]
	at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-bc01c3a-935349e]
	at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-bc01c3a-935349e]
	at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-bc01c3a-935349e]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72]
	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-bc01c3a-935349e]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot.jar:git-Spigot-bc01c3a-935349e]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-bc01c3a-935349e]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot.jar:git-Spigot-bc01c3a-935349e]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot.jar:git-Spigot-bc01c3a-935349e]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
[16:10:41] [Server thread/ERROR]: Could not call method 'public static org.bukkit.inventory.meta.ItemMeta org.bukkit.craftbukkit.v1_9_R1.inventory.CraftMetaItem$SerializableMeta.deserialize(java.util.Map) throws java.lang.Throwable' of class org.bukkit.craftbukkit.v1_9_R1.inventory.CraftMetaItem$SerializableMeta for deserialization
java.lang.IllegalArgumentException: ItemFlags([HIDE_PLACED_ON, HIDE_UNBREAKABLE, HIDE_POTION_EFFECTS, HIDE_ATTRIBUTES, HIDE_DESTROYS]) is not a valid interface java.util.Set
	at org.bukkit.craftbukkit.v1_9_R1.inventory.CraftMetaItem$SerializableMeta.getObject(CraftMetaItem.java:190) ~[spigot.jar:git-Spigot-bc01c3a-935349e]
	at org.bukkit.craftbukkit.v1_9_R1.inventory.CraftMetaItem.<init>(CraftMetaItem.java:497) ~[spigot.jar:git-Spigot-bc01c3a-935349e]
	at sun.reflect.GeneratedConstructorAccessor150.newInstance(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_72]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_72]
	at org.bukkit.craftbukkit.v1_9_R1.inventory.CraftMetaItem$SerializableMeta.deserialize(CraftMetaItem.java:155) ~[spigot.jar:git-Spigot-bc01c3a-935349e]
	at sun.reflect.GeneratedMethodAccessor318.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:77) [spigot.jar:git-Spigot-bc01c3a-935349e]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:117) [spigot.jar:git-Spigot-bc01c3a-935349e]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:195) [spigot.jar:git-Spigot-bc01c3a-935349e]
	at com.drtshock.playervaults.vaultmanagement.Serialization.deserialize(Serialization.java:152) [PlayerVaults.jar:?]
	at com.drtshock.playervaults.vaultmanagement.Serialization.deserialize(Serialization.java:147) [PlayerVaults.jar:?]
	at com.drtshock.playervaults.vaultmanagement.Serialization.toInventory(Serialization.java:93) [PlayerVaults.jar:?]
	at com.drtshock.playervaults.vaultmanagement.UUIDVaultManager.getInventory(UUIDVaultManager.java:164) [PlayerVaults.jar:?]
	at com.drtshock.playervaults.vaultmanagement.UUIDVaultManager.loadOwnVault(UUIDVaultManager.java:100) [PlayerVaults.jar:?]
	at com.drtshock.playervaults.vaultmanagement.VaultOperations.openOwnVault(VaultOperations.java:130) [PlayerVaults.jar:?]
	at com.drtshock.playervaults.vaultmanagement.VaultOperations.openOwnVault(VaultOperations.java:155) [PlayerVaults.jar:?]
	at com.drtshock.playervaults.commands.VaultCommand.onCommand(VaultCommand.java:34) [PlayerVaults.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot.jar:git-Spigot-bc01c3a-935349e]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-Spigot-bc01c3a-935349e]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) [spigot.jar:git-Spigot-bc01c3a-935349e]
	at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1314) [spigot.jar:git-Spigot-bc01c3a-935349e]
	at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1149) [spigot.jar:git-Spigot-bc01c3a-935349e]
	at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-bc01c3a-935349e]
	at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-bc01c3a-935349e]
	at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-bc01c3a-935349e]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72]
	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-bc01c3a-935349e]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot.jar:git-Spigot-bc01c3a-935349e]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-bc01c3a-935349e]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot.jar:git-Spigot-bc01c3a-935349e]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot.jar:git-Spigot-bc01c3a-935349e]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
[16:10:41] [Server thread/INFO]: [Server] Server is restarting. World is being saved.
[16:10:41] [Server thread/INFO]: CONSOLE issued server command: /kick Miloman2728 Server is restarting
[16:10:41] [Server thread/INFO]: Miloman2728 lost connection: Server is restarting
[16:10:41] [Server thread/INFO]: Miloman2728 left the game.
[16:10:41] [Server thread/INFO]: §6Player§c Console §6kicked Miloman2728 for Server is restarting.
[16:10:41] [Server thread/WARN]: handleDisconnection() called twice
[16:10:41] [Async Chat Thread - #22/INFO]: %faction §f[§4§oDeadlyAdmin§f]§f Chasen §f:§b But...
[16:10:41] [Server thread/INFO]: CONSOLE issued server command: /kick Madmant64 Server is restarting
[16:10:41] [Server thread/INFO]: Madmant64 lost connection: Server is restarting
[16:10:41] [Server thread/INFO]: Madmant64 left the game.
[16:10:41] [Server thread/INFO]: §6Player§c Console §6kicked Madmant64 for Server is restarting.
[16:10:41] [Server thread/WARN]: handleDisconnection() called twice
[16:10:42] [Server thread/INFO]: CONSOLE issued server command: /kick gamer124713 Server is restarting
[16:10:42] [Server thread/INFO]: gamer124713 lost connection: Server is restarting
[16:10:42] [Server thread/INFO]: gamer124713 left the game.
[16:10:42] [Server thread/INFO]: §6Player§c Console §6kicked gamer124713 for Server is restarting.
[16:10:42] [Server thread/WARN]: handleDisconnection() called twice
[16:10:42] [Server thread/INFO]: CONSOLE issued server command: /kick OneWithTheLives Server is restarting
[16:10:42] [Server thread/INFO]: OneWithTheLives lost connection: Server is restarting
[16:10:42] [Server thread/INFO]: OneWithTheLives left the game.
[16:10:42] [Server thread/INFO]: §6Player§c Console §6kicked OneWithTheLives for Server is restarting.
[16:10:42] [Server thread/WARN]: handleDisconnection() called twice
[16:10:42] [Server thread/INFO]: CONSOLE issued server command: /kick MrSulu Server is restarting
[16:10:42] [Server thread/INFO]: MrSulu lost connection: Server is restarting
[16:10:42] [Server thread/INFO]: MrSulu left the game.
[16:10:42] [Server thread/INFO]: §6Player§c Console §6kicked MrSulu for Server is restarting.
[16:10:42] [Server thread/WARN]: handleDisconnection() called twice
[16:10:43] [Server thread/INFO]: CONSOLE issued server command: /kick Chasen Server is restarting
[16:10:43] [Server thread/INFO]: Chasen lost connection: Server is restarting
[16:10:43] [Server thread/INFO]: Chasen left the game.
[16:10:43] [Server thread/INFO]: §6Player§c Console §6kicked Chasen for Server is restarting.
[16:10:43] [Server thread/WARN]: handleDisconnection() called twice
[16:10:43] [Server thread/INFO]: CONSOLE issued server command: /kick Lolitanicolls Server is restarting
[16:10:43] [Server thread/INFO]: Lolitanicolls lost connection: Server is restarting
[16:10:43] [Server thread/INFO]: Lolitanicolls left the game.
[16:10:43] [Server thread/INFO]: §6Player§c Console §6kicked Lolitanicolls for Server is restarting.
[16:10:43] [Server thread/WARN]: handleDisconnection() called twice
[16:10:43] [Server thread/INFO]: CONSOLE issued server command: /kick 8833rree Server is restarting
[16:10:43] [Server thread/INFO]: 8833rree lost connection: Server is restarting
[16:10:43] [Server thread/INFO]: 8833rree left the game.
[16:10:43] [Server thread/INFO]: §6Player§c Console §6kicked 8833rree for Server is restarting.
[16:10:43] [Server thread/WARN]: handleDisconnection() called twice
[16:10:43] [Server thread/INFO]: CONSOLE issued server command: /kick datdesign Server is restarting
[16:10:43] [Server thread/INFO]: datdesign lost connection: Server is restarting
[16:10:43] [Server thread/INFO]: datdesign left the game.
[16:10:43] [Server thread/INFO]: §6Player§c Console §6kicked datdesign for Server is restarting.
[16:10:43] [Server thread/WARN]: handleDisconnection() called twice
[16:10:44] [User Authenticator #26/INFO]: UUID of player Madmant64 is 1b4a0ff9-ab98-4a1a-b5e9-c77452df2f0b
[16:10:44] [Server thread/INFO]: Madmant64[/100.33.233.32:55285] logged in with

**Comment by drtshock** [comment]
@byteflux isn't this what you were getting?

**Comment by Byteflux** [comment]
I've actually encountered this issue before, and it's unrelated to what I previously reported, though it was around the same time I was messing around with attaching metadata to ItemMeta.

This issue, AFAIK, is triggered when you add item flags (e.g., `meta.setItemFlag(ItemFlag.HIDE_POTION_EFFECTS);`) and then serialize that item to PV, and then try to deserialize it by opening your PV.

The error complains that it's trying to deserialize the item flags , but assumed that it would come back as a `Set`, not a `List`. I assume this happens specifically with PV because of how it converts to JSON and back.

I personally fixed this issue by editing the deserialization code in my Spigot fork. Instead of expecting a `Set`, I changed it to a `Collection`. https://gist.github.com/Byteflux/c53bed9bbf6330498f1a

**Comment by Byteflux** [comment]
Also, this does not `crash` the server in my experience, it just prints a nasty stack trace.

**Comment by drtshock** [comment]
It doesn't fail, it just removes the item flags because it doesn't handle them.

`Trents-MacBook-Pro:19 Trent$cat plugins/PlayerVaults/uuidvaults/20737a76-497a-4bac-bb93-4693d6ff152a.yml 
vault1:
  '0': '{"==":"org.bukkit.inventory.ItemStack","type":"DIAMOND_SWORD"}'
vault2:
  '0': '{"==":"org.bukkit.inventory.ItemStack","meta":{"==":"ItemMeta","meta-type":"UNSPECIFIC","internal":"H4sIAAAAAAAAAONiYOBkEHIsKSnKTCotSfXNT8lMy0wtKuZiYGBgZGbgCA31dPHNLy5hYLgpwszACeL6pCYC+Rx3dJgZ2Bxz80vzgJIMIhwMvHBT/BJzUxkE01PzUosyk/VyEys8UhNzSjKA+v0LUosSSzLz84BaGDgYWHCoZGAAAEAW6WaYAAAA","ItemFlags":["HIDE_ATTRIBUTES"]},"type":"DIAMOND_SWORD"}'`

Where vault1 is the sword after I closed and then reopened and vault2 is where I just closed and didn't reopen the vault (to see serializing vs deserializing).

**Comment by ManBeastPig** [comment]
Still happening.
I think it might be Slimefun items if that helps.
I checked the inv of the person who opened it just as it crashed and it was fully of slimefun items and drops.
http://pastebin.com/w9nPw5gB

**Comment by drtshock** [comment]
@Byteflux rip

**Comment by Byteflux** [comment]
@drtshock AFAIK this issue was submitted before my commit made it into PV.

**Comment by ManBeastPig** [comment]
This issue is still happening. I've removed PV from my servers as it was causing total and catastrophic crashes with Slimefun items and Magic items too now.
https://www.spigotmc.org/resources/magic.1056/

**Comment by drtshock** [comment]
Can you paste the new stack trace then please (in pastebin)

**Comment by ManBeastPig** [comment]
Whats a stack trace? Error log?

**Comment by drtshock** [comment]
yes

**Comment by ManBeastPig** [comment]
Another log below.
I've now removed it from the server so i can't get any more logs.

http://pastebin.com/74utW43i

**Comment by Azfaloth** [comment]
I'm having this problem with many custom items too. I drop in an item with custom name, lore, enchants and the hide enchant flag. The items get reset back to normal nameless items and it prints this stacktrace.

http://pastebin.com/eXep5rXw

For example I had a named ender crystal called Energy Core with some lore. It also had a power enchantment which was hidden to get the enchantment glow. it also had attributes that gave speed when held in the offhand.

When the pv was opened, the item was now a completely normal ender crystal and all its data was lost.

**Comment by ManBeastPig** [comment]
I just removed playervaults. I dont think the issue is being worked on.

**Comment by drtshock** [comment]
This was fixed awhile ago.
