### ISSUE TITLE
Could not call method 'public static org.bukkit.inventory.meta.ItemMeta 

### ISSUE THREAD

**Issue by mibby** [drtshock/PlayerVaults#151]
@kashike Using PlayerVaults dev 192. Dev 190 was fine. Players are reporting their PV items are losing all their enchantments.

```
[20:02:39] [Server thread/INFO]: mibby issued server command: /pv 1
[20:02:39] [Server thread/ERROR]: Could not call method 'public static org.bukkit.inventory.meta.ItemMeta org.bukkit.craftbukkit.v1_9_R1.inventory.CraftMetaItem$SerializableMeta.deserialize(java.util.Map) throws java.lang.Throwable' of class org.bukkit.craftbukkit.v1_9_R1.inventory.CraftMetaItem$SerializableMeta for deserialization
java.lang.IllegalArgumentException: repair-cost(15) is not a valid class java.lang.Integer
	at org.bukkit.craftbukkit.v1_9_R1.inventory.CraftMetaItem$SerializableMeta.getObject(CraftMetaItem.java:190) ~[patched_1.9.jar:git-Paper-467]
	at org.bukkit.craftbukkit.v1_9_R1.inventory.CraftMetaItem.<init>(CraftMetaItem.java:492) ~[patched_1.9.jar:git-Paper-467]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_74]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_74]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_74]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_74]
	at org.bukkit.craftbukkit.v1_9_R1.inventory.CraftMetaItem$SerializableMeta.deserialize(CraftMetaItem.java:155) ~[patched_1.9.jar:git-Paper-467]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_74]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:77) [patched_1.9.jar:git-Paper-467]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:117) [patched_1.9.jar:git-Paper-467]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:195) [patched_1.9.jar:git-Paper-467]
	at com.drtshock.playervaults.vaultmanagement.Serialization.deserialize(Serialization.java:150) [PlayerVaults.jar:?]
	at com.drtshock.playervaults.vaultmanagement.Serialization.deserialize(Serialization.java:145) [PlayerVaults.jar:?]
	at com.drtshock.playervaults.vaultmanagement.Serialization.toInventory(Serialization.java:94) [PlayerVaults.jar:?]
	at com.drtshock.playervaults.vaultmanagement.UUIDVaultManager.getInventory(UUIDVaultManager.java:164) [PlayerVaults.jar:?]
	at com.drtshock.playervaults.vaultmanagement.UUIDVaultManager.loadOwnVault(UUIDVaultManager.java:100) [PlayerVaults.jar:?]
	at com.drtshock.playervaults.vaultmanagement.VaultOperations.openOwnVault(VaultOperations.java:130) [PlayerVaults.jar:?]
	at com.drtshock.playervaults.vaultmanagement.VaultOperations.openOwnVault(VaultOperations.java:155) [PlayerVaults.jar:?]
	at com.drtshock.playervaults.commands.VaultCommand.onCommand(VaultCommand.java:35) [PlayerVaults.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) [patched_1.9.jar:git-Paper-467]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) [patched_1.9.jar:git-Paper-467]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:662) [patched_1.9.jar:git-Paper-467]
	at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1367) [patched_1.9.jar:git-Paper-467]
	at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1179) [patched_1.9.jar:git-Paper-467]
	at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched_1.9.jar:git-Paper-467]
	at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) [patched_1.9.jar:git-Paper-467]
	at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.9.jar:git-Paper-467]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_74]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_74]
	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [patched_1.9.jar:git-Paper-467]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:775) [patched_1.9.jar:git-Paper-467]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.9.jar:git-Paper-467]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:714) [patched_1.9.jar:git-Paper-467]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:613) [patched_1.9.jar:git-Paper-467]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
[20:02:39] [Server thread/ERROR]: Could not call method 'public static org.bukkit.inventory.meta.ItemMeta org.bukkit.craftbukkit.v1_9_R1.inventory.CraftMetaItem$SerializableMeta.deserialize(java.util.Map) throws java.lang.Throwable' of class org.bukkit.craftbukkit.v1_9_R1.inventory.CraftMetaItem$SerializableMeta for deserialization
java.lang.IllegalArgumentException: repair-cost(2) is not a valid class java.lang.Integer
	at org.bukkit.craftbukkit.v1_9_R1.inventory.CraftMetaItem$SerializableMeta.getObject(CraftMetaItem.java:190) ~[patched_1.9.jar:git-Paper-467]
	at org.bukkit.craftbukkit.v1_9_R1.inventory.CraftMetaItem.<init>(CraftMetaItem.java:492) ~[patched_1.9.jar:git-Paper-467]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_74]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_74]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_74]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_74]
	at org.bukkit.craftbukkit.v1_9_R1.inventory.CraftMetaItem$SerializableMeta.deserialize(CraftMetaItem.java:155) ~[patched_1.9.jar:git-Paper-467]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_74]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:77) [patched_1.9.jar:git-Paper-467]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:117) [patched_1.9.jar:git-Paper-467]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:195) [patched_1.9.jar:git-Paper-467]
	at com.drtshock.playervaults.vaultmanagement.Serialization.deserialize(Serialization.java:150) [PlayerVaults.jar:?]
	at com.drtshock.playervaults.vaultmanagement.Serialization.deserialize(Serialization.java:145) [PlayerVaults.jar:?]
	at com.drtshock.playervaults.vaultmanagement.Serialization.toInventory(Serialization.java:94) [PlayerVaults.jar:?]
	at com.drtshock.playervaults.vaultmanagement.UUIDVaultManager.getInventory(UUIDVaultManager.java:164) [PlayerVaults.jar:?]
	at com.drtshock.playervaults.vaultmanagement.UUIDVaultManager.loadOwnVault(UUIDVaultManager.java:100) [PlayerVaults.jar:?]
	at com.drtshock.playervaults.vaultmanagement.VaultOperations.openOwnVault(VaultOperations.java:130) [PlayerVaults.jar:?]
	at com.drtshock.playervaults.vaultmanagement.VaultOperations.openOwnVault(VaultOperations.java:155) [PlayerVaults.jar:?]
	at com.drtshock.playervaults.commands.VaultCommand.onCommand(VaultCommand.java:35) [PlayerVaults.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) [patched_1.9.jar:git-Paper-467]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) [patched_1.9.jar:git-Paper-467]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:662) [patched_1.9.jar:git-Paper-467]
	at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1367) [patched_1.9.jar:git-Paper-467]
	at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1179) [patched_1.9.jar:git-Paper-467]
	at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched_1.9.jar:git-Paper-467]
	at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) [patched_1.9.jar:git-Paper-467]
	at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.9.jar:git-Paper-467]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_74]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_74]
	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [patched_1.9.jar:git-Paper-467]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:775) [patched_1.9.jar:git-Paper-467]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.9.jar:git-Paper-467]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:714) [patched_1.9.jar:git-Paper-467]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:613) [patched_1.9.jar:git-Paper-467]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
```

**Comment by drtshock** [comment]
@Byteflux

**Comment by Byteflux** [comment]
0562425271609ee7620741c3d6ed2c8e67970f81 should resolve it.
