### ISSUE TITLE
bug on transfer I think - http://pastebin.com/S0PtAW70

### ISSUE THREAD

**Issue by cricketcricketcricket** [drtshock/PlayerVaults#157]
I'm someplace that does not allow pastebin access :( Got another error: Ill delete if u want me to until later I can get to pastebin - it might be the same error as the other day so I included the other pastbin

[13:54:33] [Server thread/ERROR]: Could not call method 'public static org.bukkit.inventory.meta.ItemMeta org.bukkit.craftbukkit.v1_9_R1.inventory.CraftMetaItem$SerializableMeta.deserialize(java.util.Map) throws java.lang.Throwable' of class org.bukkit.craftbukkit.v1_9_R1.inventory.CraftMetaItem$SerializableMeta for deserialization
java.lang.IllegalArgumentException: ItemFlags([HIDE_ENCHANTS]) is not a valid interface java.util.Set
at org.bukkit.craftbukkit.v1_9_R1.inventory.CraftMetaItem$SerializableMeta.getObject(CraftMetaItem.java:190) ~[spigot-1.9.jar:git-Spigot-87e2f47-ef13ca4]
at org.bukkit.craftbukkit.v1_9_R1.inventory.CraftMetaItem.<init>(CraftMetaItem.java:497) ~[spigot-1.9.jar:git-Spigot-87e2f47-ef13ca4]
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_74]
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_74]
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_74]
at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_74]
at org.bukkit.craftbukkit.v1_9_R1.inventory.CraftMetaItem$SerializableMeta.deserialize(CraftMetaItem.java:155) ~[spigot-1.9.jar:git-Spigot-87e2f47-ef13ca4]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_74]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74]
at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:77) [spigot-1.9.jar:git-Spigot-87e2f47-ef13ca4]
at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:117) [spigot-1.9.jar:git-Spigot-87e2f47-ef13ca4]
at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:195) [spigot-1.9.jar:git-Spigot-87e2f47-ef13ca4]
at com.drtshock.playervaults.vaultmanagement.Serialization.deserialize(Serialization.java:152) [PlayerVaults.jar:?]
at com.drtshock.playervaults.vaultmanagement.Serialization.deserialize(Serialization.java:145) [PlayerVaults.jar:?]
at com.drtshock.playervaults.vaultmanagement.Serialization.toInventory(Serialization.java:94) [PlayerVaults.jar:?]
at com.drtshock.playervaults.vaultmanagement.UUIDVaultManager.getInventory(UUIDVaultManager.java:164) [PlayerVaults.jar:?]
at com.drtshock.playervaults.vaultmanagement.UUIDVaultManager.loadOwnVault(UUIDVaultManager.java:100) [PlayerVaults.jar:?]
at com.drtshock.playervaults.vaultmanagement.VaultOperations.openOwnVault(VaultOperations.java:130) [PlayerVaults.jar:?]
at com.drtshock.playervaults.vaultmanagement.VaultOperations.openOwnVault(VaultOperations.java:155) [PlayerVaults.jar:?]
at com.drtshock.playervaults.commands.VaultCommand.onCommand(VaultCommand.java:35) [PlayerVaults.jar:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot-1.9.jar:git-Spigot-87e2f47-ef13ca4]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.9.jar:git-Spigot-87e2f47-ef13ca4]
at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) [spigot-1.9.jar:git-Spigot-87e2f47-ef13ca4]
at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1314) [spigot-1.9.jar:git-Spigot-87e2f47-ef13ca4]
at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1149) [spigot-1.9.jar:git-Spigot-87e2f47-ef13ca4]
at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.9.jar:git-Spigot-87e2f47-ef13ca4]
at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.9.jar:git-Spigot-87e2f47-ef13ca4]
at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.jar:git-Spigot-87e2f47-ef13ca4]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_74]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_74]
at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-1.9.jar:git-Spigot-87e2f47-ef13ca4]
at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot-1.9.jar:git-Spigot-87e2f47-ef13ca4]
at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.jar:git-Spigot-87e2f47-ef13ca4]
at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.jar:git-Spigot-87e2f47-ef13ca4]
at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.jar:git-Spigot-87e2f47-ef13ca4]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]

**Comment by drtshock** [comment]
Update to the latest dev build. This should be fixed.
