### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by mibby** [drtshock/PlayerVaults#162]
PlayerVaults dev 195

```
[23:00:19] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'pv' in plugin PlayerVaults v3.5.8-SNAPSHOT-b195
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.9.2.jar:git-Paper-658]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[patched_1.9.2.jar:git-Paper-658]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:664) ~[patched_1.9.2.jar:git-Paper-658]
	at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1388) [patched_1.9.2.jar:git-Paper-658]
	at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1193) [patched_1.9.2.jar:git-Paper-658]
	at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched_1.9.2.jar:git-Paper-658]
	at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) [patched_1.9.2.jar:git-Paper-658]
	at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.9.2.jar:git-Paper-658]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_77]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_77]
	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [patched_1.9.2.jar:git-Paper-658]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:811) [patched_1.9.2.jar:git-Paper-658]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.9.2.jar:git-Paper-658]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:721) [patched_1.9.2.jar:git-Paper-658]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:620) [patched_1.9.2.jar:git-Paper-658]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
Caused by: java.lang.NullPointerException
	at com.drtshock.playervaults.vaultmanagement.Serialization.toMap(Serialization.java:45) ~[?:?]
	at com.drtshock.playervaults.vaultmanagement.Serialization.toInventory(Serialization.java:94) ~[?:?]
	at com.drtshock.playervaults.vaultmanagement.UUIDVaultManager.getInventory(UUIDVaultManager.java:164) ~[?:?]
	at com.drtshock.playervaults.vaultmanagement.UUIDVaultManager.loadOtherVault(UUIDVaultManager.java:133) ~[?:?]
	at com.drtshock.playervaults.vaultmanagement.VaultOperations.openOtherVault(VaultOperations.java:189) ~[?:?]
	at com.drtshock.playervaults.commands.VaultCommand.onCommand(VaultCommand.java:64) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.9.2.jar:git-Paper-658]
	... 15 more
```

And another error I noticed.

```
[22:52:18] [Craft Scheduler Thread - 36/WARN]: Exception in thread "Craft Scheduler Thread - 36" 
[22:52:18] [Craft Scheduler Thread - 36/WARN]: org.apache.commons.lang.UnhandledException: Plugin PlayerVaults v3.5.8-SNAPSHOT-b195 generated an exception while executing task 323488
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.yaml.snakeyaml.serializer.Serializer.anchorNode(Serializer.java:120)
	at org.yaml.snakeyaml.serializer.Serializer.serialize(Serializer.java:108)
	at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:243)
	at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:206)
	at org.yaml.snakeyaml.Yaml.dump(Yaml.java:181)
	at org.bukkit.configuration.file.YamlConfiguration.saveToString(YamlConfiguration.java:39)
	at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:68)
	at com.drtshock.playervaults.vaultmanagement.UUIDVaultManager$2.run(UUIDVaultManager.java:314)
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:58)
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 4 more
```

**Comment by mibby** [comment]
Ping pong.

@Byteflux  @kashike @drtshock 

Caused by trying to open a vault with a potion in it. Broke due to this craftbukkit commit. 
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/d39a750709e95fd38d39422b5274598731847024

**Comment by SmallSansSerif** [comment]
Yes having this error too: http://pastebin.com/BRpcNmKc

Apparently the user had spectral arrows and a regen potion.

  '15': '{"==":"org.bukkit.inventory.ItemStack","amount":4,"type":"SPECTRAL_ARROW"}'
  '19': '{"==":"org.bukkit.inventory.ItemStack","type":"POTION","meta":{"==":"ItemMeta","meta-type":"POTION","potion-type":org.bukkit.potion.PotionData@9223beb5}}'

**Comment by mibby** [comment]
Caused by https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/d39a750709e95fd38d39422b5274598731847024

Fixed in https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/420b983d59aecc1739b11916f60756933302f577

Corrupt potion meta had to be manually removed from all vaults affected. Will leave ticket open just in case one of the above I pinged wanted to look into it and have a safer way to allow opening of vaults with invalid meta.

**Comment by tuanjr** [comment]
i think i have same issue https://github.com/drtshock/PlayerVaults/issues/163

**Comment by mickcoyne** [comment]
Potions are turning into waterbottles

http://pastebin.com/vXHnbQ6c

**Comment by drtshock** [comment]
Added a null check.
