### ISSUE TITLE
SkullItem-Null wipes Pv

### ISSUE THREAD

**Issue by EthanRPro** [drtshock/PlayerVaults#165]
Currently when placing any of the skulls from the HeadsDatabase plugin will cause an inventorycloseevent exception and wipe that crate.

Plugin in conflict : https://www.spigotmc.org/resources/head-database-1300-heads.14280/

Error: 
[11:01:51] [Server thread/ERROR]: Could not pass event InventoryCloseEvent to PlayerVaults v3.5.6-b181
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-6d0ae89-a03743b]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-6d0ae89-a03743b]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-6d0ae89-a03743b]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-6d0ae89-a03743b]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:838) [spigot.jar:git-Spigot-6d0ae89-a03743b]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1384) [spigot.jar:git-Spigot-6d0ae89-a03743b]
	at net.minecraft.server.v1_8_R3.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:18) [spigot.jar:git-Spigot-6d0ae89-a03743b]
	at net.minecraft.server.v1_8_R3.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:1) [spigot.jar:git-Spigot-6d0ae89-a03743b]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-6d0ae89-a03743b]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_77]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_77]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) [spigot.jar:git-Spigot-6d0ae89-a03743b]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:718) [spigot.jar:git-Spigot-6d0ae89-a03743b]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [spigot.jar:git-Spigot-6d0ae89-a03743b]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot.jar:git-Spigot-6d0ae89-a03743b]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot.jar:git-Spigot-6d0ae89-a03743b]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
Caused by: java.lang.NullPointerException: null value in entry: skull-owner=null
	at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:33) ~[spigot.jar:git-Spigot-6d0ae89-a03743b]
	at com.google.common.collect.ImmutableMap.entryOf(ImmutableMap.java:135) ~[spigot.jar:git-Spigot-6d0ae89-a03743b]
	at com.google.common.collect.ImmutableMap$Builder.put(ImmutableMap.java:206) ~[spigot.jar:git-Spigot-6d0ae89-a03743b]
	at org.bukkit.craftbukkit.v1_8_R3.inventory.CraftMetaSkull.serialize(CraftMetaSkull.java:173) ~[spigot.jar:git-Spigot-6d0ae89-a03743b]
	at org.bukkit.craftbukkit.v1_8_R3.inventory.CraftMetaItem.serialize(CraftMetaItem.java:850) ~[spigot.jar:git-Spigot-6d0ae89-a03743b]
	at com.drtshock.playervaults.vaultmanagement.Serialization.serialize(Serialization.java:109) ~[?:?]
	at com.drtshock.playervaults.vaultmanagement.Serialization.handleSerialization(Serialization.java:119) ~[?:?]
	at com.drtshock.playervaults.vaultmanagement.Serialization.serialize(Serialization.java:109) ~[?:?]
	at com.drtshock.playervaults.vaultmanagement.Serialization.toString(Serialization.java:77) ~[?:?]
	at com.drtshock.playervaults.vaultmanagement.UUIDVaultManager.saveVault(UUIDVaultManager.java:58) ~[?:?]
	at com.drtshock.playervaults.vaultmanagement.UUIDVaultManager.saveVault(UUIDVaultManager.java:45) ~[?:?]
	at com.drtshock.playervaults.listeners.Listeners.saveVault(Listeners.java:60) ~[?:?]
	at com.drtshock.playervaults.listeners.Listeners.onClose(Listeners.java:100) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor303.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_77]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_77]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-6d0ae89-a03743b]
	... 16 more

**Comment by drtshock** [comment]
Is this still an issue on the latest update?

**Comment by drtshock** [comment]
No, this was fixed.
