### ISSUE TITLE
UTF-8 characters would bug PlayerVaults

### ISSUE THREAD

**Issue by L4BORG** [drtshock/PlayerVaults#182]
It's not the first time this happened but it looks like some UTF-8 would bug players PlayerVault (player will not be able to open his /pv anymore).

Data is stored as base64 string and from what I saw it was always named item (item name contained strange UTF-8 character(s)). I've even tried decoding that base64 string and it worked (so it was valid base64 string), yet PV would still fail to load that data and player's PV would start working again after removing that data from his .yml file.

I don't have that base64 here ATM, but I can provide exception:
```
[08:56:46] [Server thread/INFO]: Bugger issued server command: /pv 1
[08:56:46] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'pv' in plugin PlayerVaults v3.5.8-SNAPSHOT-b195
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched.jar:git-TacoSpigot-"a4a61e1"]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:143) ~[patched.jar:git-TacoSpigot-"a4a61e1"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) ~[patched.jar:git-TacoSpigot-"a4a61e1"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1194) [patched.jar:git-TacoSpigot-"a4a61e1"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1006) [patched.jar:git-TacoSpigot-"a4a61e1"]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched.jar:git-TacoSpigot-"a4a61e1"]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [patched.jar:git-TacoSpigot-"a4a61e1"]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [patched.jar:git-TacoSpigot-"a4a61e1"]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_60]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_60]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched.jar:git-TacoSpigot-"a4a61e1"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [patched.jar:git-TacoSpigot-"a4a61e1"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-TacoSpigot-"a4a61e1"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-TacoSpigot-"a4a61e1"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-TacoSpigot-"a4a61e1"]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: java.lang.NullPointerException
	at com.drtshock.playervaults.vaultmanagement.Serialization.toMap(Serialization.java:45) ~[?:?]
	at com.drtshock.playervaults.vaultmanagement.Serialization.toInventory(Serialization.java:94) ~[?:?]
	at com.drtshock.playervaults.vaultmanagement.UUIDVaultManager.getInventory(UUIDVaultManager.java:164) ~[?:?]
	at com.drtshock.playervaults.vaultmanagement.UUIDVaultManager.loadOwnVault(UUIDVaultManager.java:100) ~[?:?]
	at com.drtshock.playervaults.vaultmanagement.VaultOperations.openOwnVault(VaultOperations.java:130) ~[?:?]
	at com.drtshock.playervaults.vaultmanagement.VaultOperations.openOwnVault(VaultOperations.java:155) ~[?:?]
	at com.drtshock.playervaults.commands.VaultCommand.onCommand(VaultCommand.java:35) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched.jar:git-TacoSpigot-"a4a61e1"]
	... 15 more
```

**Comment by drtshock** [comment]
What's the string?

Also, update https://ci.drtshock.net/job/PlayerVaults/

**Comment by L4BORG** [comment]
```
[18:52:18] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'pv' in plugin PlayerVaults v3.6.0-SNAPSHOT-b202
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched.jar:git-TacoSpigot-"758e09a"]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:143) ~[patched.jar:git-TacoSpigot-"758e09a"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) ~[patched.jar:git-TacoSpigot-"758e09a"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1194) [patched.jar:git-TacoSpigot-"758e09a"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1006) [patched.jar:git-TacoSpigot-"758e09a"]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched.jar:git-TacoSpigot-"758e09a"]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [patched.jar:git-TacoSpigot-"758e09a"]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [patched.jar:git-TacoSpigot-"758e09a"]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_92]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_92]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched.jar:git-TacoSpigot-"758e09a"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [patched.jar:git-TacoSpigot-"758e09a"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-TacoSpigot-"758e09a"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-TacoSpigot-"758e09a"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-TacoSpigot-"758e09a"]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
Caused by: java.lang.ClassCastException: java.util.HashMap cannot be cast to org.bukkit.inventory.ItemStack
	at com.drtshock.playervaults.vaultmanagement.Serialization.toInventory(Serialization.java:96) ~[?:?]
	at com.drtshock.playervaults.vaultmanagement.UUIDVaultManager.getInventory(UUIDVaultManager.java:161) ~[?:?]
	at com.drtshock.playervaults.vaultmanagement.UUIDVaultManager.loadOwnVault(UUIDVaultManager.java:101) ~[?:?]
	at com.drtshock.playervaults.vaultmanagement.VaultOperations.openOwnVault(VaultOperations.java:150) ~[?:?]
	at com.drtshock.playervaults.vaultmanagement.VaultOperations.openOwnVault(VaultOperations.java:175) ~[?:?]
	at com.drtshock.playervaults.commands.VaultCommand.onCommand(VaultCommand.java:35) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched.jar:git-TacoSpigot-"758e09a"]
	... 15 more
```

.yml file:
```
vault1:
  '0': !!binary |-
    eyI9PSI6Im9yZy5idWtraXQuaW52ZW50b3J5Lkl0ZW1TdGFjayIsInR5cGUiOiJCT1ciLCJtZXRhIjp7Ij09IjoiSXRlbU1ldGEiLCJtZXRhLXR5cGUiOiJVTlNQRUNJRklDIiwiZW5jaGFudHMiOnsiQVJST1dfS05PQ0tCQUNLIjoyLCJEVVJBQklMSVRZIjozLCJBUlJPV19GSVJFIjoxLCJBUlJPV19EQU1BR0UiOjV9LCJkaXNwbGF5LW5hbWUiOiLwnZOt8J2TuPCdlIA/8J2TrfCdk7jwnZSA8J2TtyIsInJlcGFpci1jb3N0IjozMX19
```

base64 string can be decoded with ie https://www.base64decode.org/ so I'm  not sure what is the issue... decoded:

```
{"==":"org.bukkit.inventory.ItemStack","type":"BOW","meta":{"==":"ItemMeta","meta-type":"UNSPECIFIC","enchants":{"ARROW_KNOCKBACK":2,"DURABILITY":3,"ARROW_FIRE":1,"ARROW_DAMAGE":5},"display-name":"𝓭𝓸𝔀?𝓭𝓸𝔀𝓷","repair-cost":31}}
```

Tho I'm not sure if that "?" was there or something else that got replaced by "?"... but players have one or more of those "invalid" items won't be able to use their /pv's anymore... (until that item is removed).

**Comment by drtshock** [comment]
You weren't originally using playervaults. That's not how we save files.

**Comment by L4BORG** [comment]
WTH? I was using PlayerVaults since day 1... :/ and this user had no access to /pv until 1 or 2 months ago...

**Comment by drtshock** [comment]
```    eyI9PSI6Im9yZy5idWtraXQuaW52ZW50b3J5Lkl0ZW1TdGFjayIsInR5cGUiOiJCT1ciLCJtZXRhIjp7Ij09IjoiSXRlbU1ldGEiLCJtZXRhLXR5cGUiOiJVTlNQRUNJRklDIiwiZW5jaGFudHMiOnsiQVJST1dfS05PQ0tCQUNLIjoyLCJEVVJBQklMSVRZIjozLCJBUlJPV19GSVJFIjoxLCJBUlJPV19EQU1BR0UiOjV9LCJkaXNwbGF5LW5hbWUiOiLwnZOt8J2TuPCdlIA/8J2TrfCdk7jwnZSA8J2TtyIsInJlcGFpci1jb3N0IjozMX19
```
is not from playervaults

**Comment by L4BORG** [comment]
It's base64 encoded string... not sure where it's coming from then lol... it's stored in PV files... and if you decode it you would get serialized PV item....

**Comment by L4BORG** [comment]
Could it be JSONObject generating base64 encoded strings.. ?

**Comment by drtshock** [comment]
no
