### ISSUE TITLE
Got this on shutdown today after update to dev build 5-30-16

### ISSUE THREAD

**Issue by larrycatania** [drtshock/PlayerVaults#183]
3:39] [Server thread/INFO]: [GlowGUI] Disabling the plugin...
[19:33:39] [Server thread/INFO]: [GlowGUI] Disabled GlowGUI v1.0.8!
[19:33:39] [Server thread/INFO]: [PlayerVaults] Disabling PlayerVaults v3.6.0-SNAPSHOT-b201
[19:33:39] [Server thread/INFO]: [Duels] Disabling Duels v1.1.1
[19:33:39] [Server thread/INFO]: [Multiverse-Inventories] Disabling Multiverse-Inventories v2.5-b410
[19:33:39] [Server thread/ERROR]: Error occurred while disabling Multiverse-Inventories v2.5-b410 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
	at com.onarandombox.multiverseinventories.MultiverseInventories.onDisable(MultiverseInventories.java:76) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:294) ~[spigot.jar:git-Spigot-4af49dc-4e19de1]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:364) [spigot.jar:git-Spigot-4af49dc-4e19de1]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [spigot.jar:git-Spigot-4af49dc-4e19de1]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417) [spigot.jar:git-Spigot-4af49dc-4e19de1]
	at org.bukkit.craftbukkit.v1_9_R2.CraftServer.disablePlugins(CraftServer.java:340) [spigot.jar:git-Spigot-4af49dc-4e19de1]
	at net.minecraft.server.v1_9_R2.MinecraftServer.stop(MinecraftServer.java:459) [spigot.jar:git-Spigot-4af49dc-4e19de1]
	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:600) [spigot.jar:git-Spigot-4af49dc-4e19de1]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
[19:33:39] [Server thread/INFO]: [MythicMobs] Disabling MythicMobs v2.4.4
[19:33:39] [Server thread/INFO]: [MythicMobs] Disabling Mythic Mobs...

**Comment by kashike** [comment]
It sounds like you are running an old version of CraftBukkit.

**Comment by drtshock** [comment]
+ it's with a different plugin..
