### ISSUE TITLE
NumberFormatException

### ISSUE THREAD

**Issue by mibby** [drtshock/PlayerVaults#205]
Noticed this error in my logs from a player.

PlayerVaults dev 205

```
[15:02:42] [Server thread/INFO]: mibby issued server command: /pv 4 mibby
[15:02:42] [Server thread/INFO]: At opening other vault. Time since start: 181ms
[15:02:42] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'pv' in plugin PlayerVaults v3.6.0-SNAPSHOT-b205
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.10.2.jar:git-Paper-808]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152) ~[patched_1.10.2.jar:git-Paper-808]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:665) ~[patched_1.10.2.jar:git-Paper-808]
	at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1389) [patched_1.10.2.jar:git-Paper-808]
	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1194) [patched_1.10.2.jar:git-Paper-808]
	at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched_1.10.2.jar:git-Paper-808]
	at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) [patched_1.10.2.jar:git-Paper-808]
	at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.10.2.jar:git-Paper-808]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_92]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_92]
	at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [patched_1.10.2.jar:git-Paper-808]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:796) [patched_1.10.2.jar:git-Paper-808]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.10.2.jar:git-Paper-808]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:730) [patched_1.10.2.jar:git-Paper-808]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:629) [patched_1.10.2.jar:git-Paper-808]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
Caused by: java.lang.NumberFormatException: For input string: "mibby"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_92]
	at java.lang.Integer.parseInt(Integer.java:580) ~[?:1.8.0_92]
	at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_92]
	at com.drtshock.playervaults.commands.VaultCommand.onCommand(VaultCommand.java:63) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.10.2.jar:git-Paper-808]
	... 15 more
```

```
[00:44:46] [Server thread/INFO]: player issued server command: /chest 1 player
[00:44:46] [Server thread/INFO]: At opening other vault. Time since start: 169ms
[00:44:46] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'chest' in plugin PlayerVaults v3.6.0-SNAPSHOT-b205
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.10.2.jar:git-Paper-809]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152) ~[patched_1.10.2.jar:git-Paper-809]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:665) ~[patched_1.10.2.jar:git-Paper-809]
	at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1389) [patched_1.10.2.jar:git-Paper-809]
	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1194) [patched_1.10.2.jar:git-Paper-809]
	at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched_1.10.2.jar:git-Paper-809]
	at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) [patched_1.10.2.jar:git-Paper-809]
	at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.10.2.jar:git-Paper-809]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_92]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_92]
	at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [patched_1.10.2.jar:git-Paper-809]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:796) [patched_1.10.2.jar:git-Paper-809]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.10.2.jar:git-Paper-809]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:730) [patched_1.10.2.jar:git-Paper-809]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:629) [patched_1.10.2.jar:git-Paper-809]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
Caused by: java.lang.NumberFormatException: For input string: "player"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_92]
	at java.lang.Integer.parseInt(Integer.java:580) ~[?:1.8.0_92]
	at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_92]
	at com.drtshock.playervaults.commands.VaultCommand.onCommand(VaultCommand.java:63) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.10.2.jar:git-Paper-809]
	... 15 more
[00:44:50] [Server thread/INFO]: player issued server command: /chest 1 player2
[00:44:50] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'chest' in plugin PlayerVaults v3.6.0-SNAPSHOT-b205
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.10.2.jar:git-Paper-809]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152) ~[patched_1.10.2.jar:git-Paper-809]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:665) ~[patched_1.10.2.jar:git-Paper-809]
	at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1389) [patched_1.10.2.jar:git-Paper-809]
	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1194) [patched_1.10.2.jar:git-Paper-809]
	at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched_1.10.2.jar:git-Paper-809]
	at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) [patched_1.10.2.jar:git-Paper-809]
	at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.10.2.jar:git-Paper-809]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_92]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_92]
	at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [patched_1.10.2.jar:git-Paper-809]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:796) [patched_1.10.2.jar:git-Paper-809]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.10.2.jar:git-Paper-809]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:730) [patched_1.10.2.jar:git-Paper-809]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:629) [patched_1.10.2.jar:git-Paper-809]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
Caused by: java.lang.NumberFormatException: For input string: "player2"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_92]
	at java.lang.Integer.parseInt(Integer.java:580) ~[?:1.8.0_92]
	at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_92]
	at com.drtshock.playervaults.commands.VaultCommand.onCommand(VaultCommand.java:63) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.10.2.jar:git-Paper-809]
	... 15 more
```

**Comment by drtshock** [comment]
Ah, interesting. Should be /pv mibby 4 but looks like I don't handle an invalid case correctly.

**Comment by mibby** [comment]
Yeah. :P I didn't type the command, just saw these errors in my logs. Catching invalid case / command input should probably be added. They also tried ```/pv 4 player 2```.
