### ISSUE TITLE
Items with "strange names" bugging players PV's...

### ISSUE THREAD

**Issue by L4BORG** [drtshock/PlayerVaults#207]
How to replicate this?

Take anvil, take random item, rename item on anvil and use this as name (not sure if you can copy paste this via web without changing invalid utf-8 characters I've originally copied them from here: http://www.cl.cam.ac.uk/~mgk25/ucs/examples/UTF-8-test.txt for testing):

𐀀𐀀𐀀�����"𐀀"κόσμε

put renamed item into your /pv 1 close it... boom, now you can't open your /pv 1 anymore.

it's actually not cause by "κόσμε" but some random (invalid) UTF-8 characters I've copied from http://www.cl.cam.ac.uk/~mgk25/ucs/examples/UTF-8-test.txt

My guess is JSONObject would recognize this as binary data and created this:

https://github.com/drtshock/PlayerVaults/issues/182

Of course decoding this is not supported for some reason, which is why that /pv would be bugged from that point on... with Ex:

```
[08:56:46] [Server thread/INFO]: Bugger issued server command: /pv 1
[08:56:46] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'pv' in plugin PlayerVaults v3.5.8-SNAPSHOT-b195
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched.jar:git-TacoSpigot-"a4a61e1"]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:143) ~[patched.jar:git-TacoSpigot-"a4a61e1"]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) ~[patched.jar:git-TacoSpigot-"a4a61e1"]
    at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1194) [patched.jar:git-TacoSpigot-"a4a61e1"]
    at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1006) [patched.jar:git-TacoSpigot-"a4a61e1"]
    at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched.jar:git-TacoSpigot-"a4a61e1"]
    at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [patched.jar:git-TacoSpigot-"a4a61e1"]
    at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [patched.jar:git-TacoSpigot-"a4a61e1"]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_60]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_60]
    at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched.jar:git-TacoSpigot-"a4a61e1"]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [patched.jar:git-TacoSpigot-"a4a61e1"]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-TacoSpigot-"a4a61e1"]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-TacoSpigot-"a4a61e1"]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-TacoSpigot-"a4a61e1"]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: java.lang.NullPointerException
    at com.drtshock.playervaults.vaultmanagement.Serialization.toMap(Serialization.java:45) ~[?:?]
    at com.drtshock.playervaults.vaultmanagement.Serialization.toInventory(Serialization.java:94) ~[?:?]
    at com.drtshock.playervaults.vaultmanagement.UUIDVaultManager.getInventory(UUIDVaultManager.java:164) ~[?:?]
    at com.drtshock.playervaults.vaultmanagement.UUIDVaultManager.loadOwnVault(UUIDVaultManager.java:100) ~[?:?]
    at com.drtshock.playervaults.vaultmanagement.VaultOperations.openOwnVault(VaultOperations.java:130) ~[?:?]
    at com.drtshock.playervaults.vaultmanagement.VaultOperations.openOwnVault(VaultOperations.java:155) ~[?:?]
    at com.drtshock.playervaults.commands.VaultCommand.onCommand(VaultCommand.java:35) ~[?:?]
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched.jar:git-TacoSpigot-"a4a61e1"]
    ... 15 more
```

File was generated and modified only by PV and I'm sure you should be now able to replicate this...

**Comment by ZombieHDGaming** [comment]
First off, let me say that, drtshock closed your last issue because it was not an issue on PlayerVaults side, so please do not reference that. Second, if you are having an issue with "invalid" UTF-8 chars (Why would you do testing with invalid ones? That just seems idiotic IMO), then test it with regular supported UTF-8 chars and see if your problem continues. Third, and finally, I would suggest updating both PlayerVaults (if you din't have the newest dev build) and your server, as I am not one to use TacoSpigot, I doubt that it may support this.

Also, I just did my own testing with UTF-8 chars and PlayerVaults, and it works just fine. I took a random one on a website, and changed a diamond sword's name to the char, and left the server and reopened the vault, and it worked just fine dude. I am using Spigot 1.10.2 granted, but still. The problem is on your end, not the plugin. I have tested and confirmed this, so this is your issue, not drtshock's.

**Comment by L4BORG** [comment]
TacoSpigot is just PaperSpigot with a few extra Patchs that shouldn't affect PV...

Now the problem is, players can get those characters into their PVs and bug them. 

I was testing invalid UTF8 characters because that was the only way to replicate error, since I was unable to decode base64 data (invalid characters would be missing, you can try decoding that base64 string yourself).

**Comment by L4BORG** [comment]
Also, I've tested this on build #203.

**Comment by drtshock** [comment]
Yes please try to reproduce on regular spigot with build 205 of playervaults.

We don't do base 64 encoding though. We use Bukkit's built in serialization which is pretty human readable.

**Comment by L4BORG** [comment]
Done, same thing happened...

I've created new item (anvil) and rename it on anvil as described... there were no errors when I put item (renamed anvil) in /pv 1, but after I tried opening /pv 1 again:

```
[23:38:44] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'pv' in plugin PlayerVaults v3.6.0-SNAPSHOT-b205
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-dev.jar:git-Spigot-e4d4710-e1ebe52]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-dev.jar:git-Spigot-e4d4710-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot-dev.jar:git-Spigot-e4d4710-e1ebe52]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot-dev.jar:git-Spigot-e4d4710-e1ebe52]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot-dev.jar:git-Spigot-e4d4710-e1ebe52]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-dev.jar:git-Spigot-e4d4710-e1ebe52]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-dev.jar:git-Spigot-e4d4710-e1ebe52]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-dev.jar:git-Spigot-e4d4710-e1ebe52]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_92]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_92]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-dev.jar:git-Spigot-e4d4710-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot-dev.jar:git-Spigot-e4d4710-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-dev.jar:git-Spigot-e4d4710-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-dev.jar:git-Spigot-e4d4710-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-dev.jar:git-Spigot-e4d4710-e1ebe52]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
Caused by: java.lang.ClassCastException: java.util.HashMap cannot be cast to org.bukkit.inventory.ItemStack
	at com.drtshock.playervaults.vaultmanagement.Serialization.toInventory(Serialization.java:96) ~[?:?]
	at com.drtshock.playervaults.vaultmanagement.UUIDVaultManager.getInventory(UUIDVaultManager.java:161) ~[?:?]
	at com.drtshock.playervaults.vaultmanagement.UUIDVaultManager.loadOwnVault(UUIDVaultManager.java:101) ~[?:?]
	at com.drtshock.playervaults.vaultmanagement.VaultOperations.openOwnVault(VaultOperations.java:150) ~[?:?]
	at com.drtshock.playervaults.vaultmanagement.VaultOperations.openOwnVault(VaultOperations.java:175) ~[?:?]
	at com.drtshock.playervaults.commands.VaultCommand.onCommand(VaultCommand.java:35) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-dev.jar:git-Spigot-e4d4710-e1ebe52]
	... 15 more
```

.yml file that was generated:
```
vault1:
  '0': !!binary |-
    eyI9PSI6Im9yZy5idWtraXQuaW52ZW50b3J5Lkl0ZW1TdGFjayIsInR5cGUiOiJBTlZJTCIsIm1ldGEiOnsiPT0iOiJJdGVtTWV0YSIsIm1ldGEtdHlwZSI6IlVOU1BFQ0lGSUMiLCJkaXNwbGF5LW5hbWUiOiLvv73wkICA8JCAgPCQgIDvv73vv73vv73vv73vv71cIvCQgIAiLCJyZXBhaXItY29zdCI6MX19
```

and if you decode that base64 (I have NO idea where that came from) you get
```
{"==":"org.bukkit.inventory.ItemStack","type":"ANVIL","meta":{"==":"ItemMeta","meta-type":"UNSPECIFIC","display-name":"�𐀀𐀀𐀀�����\"𐀀","repair-cost":1}}
```

I'd say it's clear that "display-name" is the issue here, but dunno where that base64 is coming from...

```
>ver
[23:39:36 INFO]: This server is running CraftBukkit version git-Spigot-e4d4710-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
[23:39:36 INFO]: Checking version, please wait...
[23:39:37 INFO]: You are 357 version(s) behind
```

IIRC this is latest 1.8.8 and I've tested with latest PlayerVaults.

**Comment by L4BORG** [comment]
Oh and yeah what was with or without -Dfile.encoding=UTF-8 flag.

**Comment by drtshock** [comment]
Thank you for all the info. I'll look into it hopefully over the weekend when I have some time :)

**Comment by L4BORG** [comment]
Example of invalid data:

```
  '8': !!binary |-
    eyI9PSI6Im9yZy5idWtraXQuaW52ZW50b3J5Lkl0ZW1TdGFjayIsImRhbWFnZSI6MjUyLCJ0eXBlIjoiRElBTU9ORF9TV09SRCIsIm1ldGEiOnsiPT0iOiJJdGVtTWV0YSIsIm1ldGEtdHlwZSI6IlVOU1BFQ0lGSUMiLCJlbmNoYW50cyI6eyJEVVJBQklMSVRZIjoxLCJGSVJFX0FTUEVDVCI6MSwiTE9PVF9CT05VU19NT0JTIjoxLCJEQU1BR0VfQUxMIjoyfSwiZGlzcGxheS1uYW1lIjoiQXJpYSDwn5C88J+QvOKdpCAiLCJyZXBhaXItY29zdCI6MX19
```

You can decode that with https://www.base64decode.org/ but I have no idea what is causing it and how it's getting there...
