### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by Gigorahk** [drtshock/PlayerVaults#210]
Hey I've been using your plugin for a bit and am suddenly getting this error. It spams my console constantly and appears to be lagging the server. It keeps repeating the same thing over and over again. I really like this plugin and players have their stuff stored inside so I cannot try to reset the plugin or anything, please help.

16.07 17:34:24 [Server] ERROR Could not pass event InventoryClickEvent to PlayerVaults v3.5.6-b181 16.07 17:34:24 [Server] INFO org.bukkit.event.EventException 16.07 17:34:24 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[craftbukkit-1.10_BT52_07_13.jar:git-Bukkit-301db84] 16.07 17:34:24 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit-1.10_BT52_07_13.jar:git-Bukkit-301db84] 16.07 17:34:24 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [craftbukkit-1.10_BT52_07_13.jar:git-Bukkit-301db84] 16.07 17:34:24 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [craftbukkit-1.10_BT52_07_13.jar:git-Bukkit-301db84] 16.07 17:34:24 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1792) [craftbukkit-1.10_BT52_07_13.jar:git-Bukkit-301db84] 16.07 17:34:24 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInWindowClick.a(SourceFile:33) [craftbukkit-1.10_BT52_07_13.jar:git-Bukkit-301db84] 16.07 17:34:24 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInWindowClick.a(SourceFile:10) [craftbukkit-1.10_BT52_07_13.jar:git-Bukkit-301db84] 16.07 17:34:24 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit-1.10_BT52_07_13.jar:git-Bukkit-301db84] 16.07 17:34:24 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_92] 16.07 17:34:24 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_92] 16.07 17:34:24 [Server] INFO at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [craftbukkit-1.10_BT52_07_13.jar:git-Bukkit-301db84] 16.07 17:34:24 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:692) [craftbukkit-1.10_BT52_07_13.jar:git-Bukkit-301db84] 16.07 17:34:24 [Server] INFO at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:360) [craftbukkit-1.10_BT52_07_13.jar:git-Bukkit-301db84] 16.07 17:34:24 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:647) [craftbukkit-1.10_BT52_07_13.jar:git-Bukkit-301db84] 16.07 17:34:24 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:551) [craftbukkit-1.10_BT52_07_13.jar:git-Bukkit-301db84] 16.07 17:34:24 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92] 16.07 17:34:24 [Server] INFO Caused by: java.lang.NoSuchMethodError: org.bukkit.event.inventory.InventoryClickEvent.getClickedInventory()Lorg/bukkit/inventory/Inventory; 16.07 17:34:24 [Server] INFO at com.drtshock.playervaults.listeners.Listeners.onClick(Listeners.java:243) ~[?:?] 16.07 17:34:24 [Server] INFO at sun.reflect.GeneratedMethodAccessor388.invoke(Unknown Source) ~[?:?] 16.07 17:34:24 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_92] 16.07 17:34:24 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_92] 16.07 17:34:24 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[craftbukkit-1.10_BT52_07_13.jar:git-Bukkit-301db84] 16.07 17:34:24 [Server] INFO ... 15 more

Another Error (They appear to be the same)

16.07 17:35:33 [Server] ERROR Could not pass event InventoryClickEvent to PlayerVaults v3.5.6-b181 16.07 17:35:33 [Server] INFO org.bukkit.event.EventException 16.07 17:35:33 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[craftbukkit-1.10_BT52_07_13.jar:git-Bukkit-301db84] 16.07 17:35:33 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit-1.10_BT52_07_13.jar:git-Bukkit-301db84] 16.07 17:35:33 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [craftbukkit-1.10_BT52_07_13.jar:git-Bukkit-301db84] 16.07 17:35:33 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [craftbukkit-1.10_BT52_07_13.jar:git-Bukkit-301db84] 16.07 17:35:33 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1792) [craftbukkit-1.10_BT52_07_13.jar:git-Bukkit-301db84] 16.07 17:35:33 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInWindowClick.a(SourceFile:33) [craftbukkit-1.10_BT52_07_13.jar:git-Bukkit-301db84] 16.07 17:35:33 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInWindowClick.a(SourceFile:10) [craftbukkit-1.10_BT52_07_13.jar:git-Bukkit-301db84] 16.07 17:35:33 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit-1.10_BT52_07_13.jar:git-Bukkit-301db84] 16.07 17:35:33 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_92] 16.07 17:35:33 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_92] 16.07 17:35:33 [Server] INFO at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [craftbukkit-1.10_BT52_07_13.jar:git-Bukkit-301db84] 16.07 17:35:33 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:692) [craftbukkit-1.10_BT52_07_13.jar:git-Bukkit-301db84] 16.07 17:35:33 [Server] INFO at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:360) [craftbukkit-1.10_BT52_07_13.jar:git-Bukkit-301db84] 16.07 17:35:33 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:647) [craftbukkit-1.10_BT52_07_13.jar:git-Bukkit-301db84] 16.07 17:35:33 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:551) [craftbukkit-1.10_BT52_07_13.jar:git-Bukkit-301db84] 16.07 17:35:33 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92] 16.07 17:35:33 [Server] INFO Caused by: java.lang.NoSuchMethodError: org.bukkit.event.inventory.InventoryClickEvent.getClickedInventory()Lorg/bukkit/inventory/Inventory; 16.07 17:35:33 [Server] INFO at com.drtshock.playervaults.listeners.Listeners.onClick(Listeners.java:243) ~[?:?] 16.07 17:35:33 [Server] INFO at sun.reflect.GeneratedMethodAccessor388.invoke(Unknown Source) ~[?:?] 16.07 17:35:33 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_92] 16.07 17:35:33 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_92] 16.07 17:35:33 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[craftbukkit-1.10_BT52_07_13.jar:git-Bukkit-301db84] 16.07 17:35:33 [Server] INFO ... 15 more

**Comment by Gigorahk** [comment]
It literally spams this error every few seconds constantly.

**Comment by Gigorahk** [comment]
17.07 00:15:39 [Server] ERROR Could not pass event InventoryClickEvent to PlayerVaults v3.5.6-b181
17.07 00:15:39 [Server] INFO org.bukkit.event.EventException
17.07 00:15:39 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[craftbukkit-1.10_BT52_07_13.jar:git-Bukkit-301db84]
17.07 00:15:39 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit-1.10_BT52_07_13.jar:git-Bukkit-301db84]
17.07 00:15:39 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [craftbukkit-1.10_BT52_07_13.jar:git-Bukkit-301db84]
17.07 00:15:39 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [craftbukkit-1.10_BT52_07_13.jar:git-Bukkit-301db84]
17.07 00:15:39 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1792) [craftbukkit-1.10_BT52_07_13.jar:git-Bukkit-301db84]
17.07 00:15:39 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInWindowClick.a(SourceFile:33) [craftbukkit-1.10_BT52_07_13.jar:git-Bukkit-301db84]
17.07 00:15:39 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInWindowClick.a(SourceFile:10) [craftbukkit-1.10_BT52_07_13.jar:git-Bukkit-301db84]
17.07 00:15:39 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit-1.10_BT52_07_13.jar:git-Bukkit-301db84]
17.07 00:15:39 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_92]
17.07 00:15:39 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_92]
17.07 00:15:39 [Server] INFO at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [craftbukkit-1.10_BT52_07_13.jar:git-Bukkit-301db84]
17.07 00:15:39 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:692) [craftbukkit-1.10_BT52_07_13.jar:git-Bukkit-301db84]
17.07 00:15:39 [Server] INFO at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:360) [craftbukkit-1.10_BT52_07_13.jar:git-Bukkit-301db84]
17.07 00:15:39 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:647) [craftbukkit-1.10_BT52_07_13.jar:git-Bukkit-301db84]
17.07 00:15:39 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:551) [craftbukkit-1.10_BT52_07_13.jar:git-Bukkit-301db84]
17.07 00:15:39 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
17.07 00:15:39 [Server] INFO Caused by: java.lang.NoSuchMethodError: org.bukkit.event.inventory.InventoryClickEvent.getClickedInventory()Lorg/bukkit/inventory/Inventory;
17.07 00:15:39 [Server] INFO at com.drtshock.playervaults.listeners.Listeners.onClick(Listeners.java:243) ~[?:?]
17.07 00:15:39 [Server] INFO at sun.reflect.GeneratedMethodAccessor268.invoke(Unknown Source) ~[?:?]
17.07 00:15:39 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_92]
17.07 00:15:39 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_92]
17.07 00:15:39 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[craftbukkit-1.10_BT52_07_13.jar:git-Bukkit-301db84]
17.07 00:15:39 [Server] INFO ... 15 more

**Comment by Gigorahk** [comment]
I changed to Spigot and it seems to have stopped.
