### ISSUE TITLE
Plugin don't load

### ISSUE THREAD

**Issue by bertek41** [drtshock/PlayerVaults#265]
Spigot 1.8.8 Java 8 Im tried latest dev build and latest on bukkit & spigot page errors: `[22:33:08] [Server thread/ERROR]: Could not load 'plugins/PlayerVaults.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.IllegalArgumentException: Plugin already initialized!
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[craftbukkit.jar:git-Spigot-5f38d38-12698ea]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[craftbukkit.jar:git-Spigot-5f38d38-12698ea]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:275) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:292) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.IllegalArgumentException: Plugin already initialized!
	at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:122) ~[craftbukkit.jar:git-Spigot-5f38d38-12698ea]
	at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:66) ~[craftbukkit.jar:git-Spigot-5f38d38-12698ea]
	at com.drtshock.playervaults.PlayerVaults.<init>(PlayerVaults.java:58) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_101]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_101]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_101]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_101]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_101]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) ~[craftbukkit.jar:git-Spigot-5f38d38-12698ea]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[craftbukkit.jar:git-Spigot-5f38d38-12698ea]
	... 6 more
Caused by: java.lang.IllegalStateException: Initial initialization
	at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:125) ~[craftbukkit.jar:git-Spigot-5f38d38-12698ea]
	at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:66) ~[craftbukkit.jar:git-Spigot-5f38d38-12698ea]
	at com.massivecraft.factions.zcore.MPlugin.<init>(MPlugin.java:28) ~[?:?]
	at com.massivecraft.factions.P.<init>(P.java:62) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_101]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_101]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_101]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_101]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_101]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) ~[craftbukkit.jar:git-Spigot-5f38d38-12698ea]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[craftbukkit.jar:git-Spigot-5f38d38-12698ea]
	... 6 more`

**Comment by kashike** [comment]
> Plugin already initialized!

It sounds like you're trying to load PlayerVaults twice.

**Comment by bertek41** [comment]
I just start server :D

**Comment by bertek41** [comment]
I deleted plugin then re-upload it but nothing changed

**Comment by Deathworld** [comment]
I have the same error when I'm using this plugin :  https://www.spigotmc.org/resources/%E2%9E%B9randomtp%E2%9E%B7%E2%9D%B0original%E2%9D%B1-best-sign-random-teleport-plugin-new-open-source-and-api.5084/

Could you please fix it ? :3 
Thanks !

**Comment by Tara3208** [comment]
Having the same error with PlayerVaults, the error seems invalid as no other plugin is made by the same Developer and should be using the same classpath >.< Well, besides FactionUUID but that's completely different.

**Comment by AlexTeal03** [comment]
im getting the same issue

**Comment by drtshock** [comment]
Try the latest update. Usually a fresh download fixes this.
