### ISSUE TITLE
Cant load plugin

### ISSUE THREAD

**Issue by AlexTeal03** [drtshock/PlayerVaults#315]
Plugin wont work.
[15:10:08 ERROR]: Could not load 'plugins/PlayerVaults.jar' in folder 'plugins'

**Comment by drtshock** [comment]
Full error please.

**Comment by AlexTeal03** [comment]
[18:48:16 ERROR]: Could not load 'plugins/PlayerVaults.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.IllegalArgumentException: Plugin already initialized!
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:275) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:292) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.reload(CraftServer.java:739) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.Bukkit.reload(Bukkit.java:535) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at gyurix.commands.CustomCommandMap.dispatch(CustomCommandMap.java:89) [SpigotLib.jar:?]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:576) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at ch.njol.skript.Skript.dispatchCommand(Skript.java:944) [Skript.jar:?]
        at ch.njol.skript.effects.EffCommand.execute(EffCommand.java:86) [Skript.jar:?]
        at ch.njol.skript.lang.Effect.run(Effect.java:50) [Skript.jar:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:63) [Skript.jar:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:91) [Skript.jar:?]
        at ch.njol.skript.effects.Delay$1.run(Delay.java:85) [Skript.jar:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: java.lang.IllegalArgumentException: Plugin already initialized!
        at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:122) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:66) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at com.drtshock.playervaults.PlayerVaults.<init>(PlayerVaults.java:58) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_112]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_112]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_112]
 #2: LINE 757 in FILE Main.java (gyurix.spigotlib.Main.resetConfig)
 #3: LINE 529 in FILE Main.java (gyurix.spigotlib.Main.onLoad)
 #4: LINE 89 in FILE CustomCommandMap.java (gyurix.commands.CustomCommandMap.dispatch)

**Comment by drtshock** [comment]
Says you have two copies of the plugin. Make sure you don’t. :)
