### ISSUE TITLE
IllegalStateException: Cannot into itemstacksz! | NullPointerException: null value in entry: meta-type=null

### ISSUE THREAD

**Issue by mibby** [drtshock/PlayerVaults#330]
PlayerVaultsX compiled as of commit https://github.com/drtshock/PlayerVaults/commit/41ea3fde09a32c297cba248fabae9321b215a38f

Had a user complain that they were missing some items from their 3rd player vault and that they didn't remove anything. Upon comparing both files (pre and post conversion), you can see there is nothing in the vault.

Old uuid vault file.
https://paste.ubuntu.com/26480421/

Base64 uuid file.
https://paste.ubuntu.com/26480416/

Is there an issue with conversions on some of the items in that vault3? Also is there no way to keep the legibility of the old storage file? As the old formatting was significantly easier to figure out what items people had in their pvs for recovery, and especially if you wanted to do bulk edits to remove anything people may have obtained.

**Comment by mibby** [comment]
Going through the logs, I noticed this error when they tried to open their 3rd vault.

```
[09:14:47] [Server thread/ERROR]: Could not pass event InventoryCloseEvent to PlayerVaults v4.0.2-SNAPSHOT
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1318]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.12.2.jar:git-Paper-1318]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1318]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) ~[patched_1.12.2.jar:git-Paper-1318]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) ~[patched_1.12.2.jar:git-Paper-1318]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:932) ~[patched_1.12.2.jar:git-Paper-1318]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1761) ~[patched_1.12.2.jar:git-Paper-1318]
	at net.minecraft.server.v1_12_R1.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:18) ~[patched_1.12.2.jar:git-Paper-1318]
	at net.minecraft.server.v1_12_R1.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:5) ~[patched_1.12.2.jar:git-Paper-1318]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1318]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_162]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_162]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.2.jar:git-Paper-1318]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [patched_1.12.2.jar:git-Paper-1318]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1318]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1318]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1318]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
Caused by: java.lang.IllegalStateException: Cannot into itemstacksz!
	at com.drtshock.playervaults.vaultmanagement.Base64Serialization.toBase64(Base64Serialization.java:36) ~[PlayerVaultsX.jar:?]
	at com.drtshock.playervaults.vaultmanagement.VaultManager.saveVault(VaultManager.java:42) ~[PlayerVaultsX.jar:?]
	at com.drtshock.playervaults.listeners.Listeners.saveVault(Listeners.java:59) ~[PlayerVaultsX.jar:?]
	at com.drtshock.playervaults.listeners.Listeners.onClose(Listeners.java:94) ~[PlayerVaultsX.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor254.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1318]
	... 17 more
Caused by: java.lang.NullPointerException: null value in entry: meta-type=null
	at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:34) ~[patched_1.12.2.jar:git-Paper-1318]
	at com.google.common.collect.ImmutableMapEntry.<init>(ImmutableMapEntry.java:49) ~[patched_1.12.2.jar:git-Paper-1318]
	at com.google.common.collect.ImmutableMap.entryOf(ImmutableMap.java:172) ~[patched_1.12.2.jar:git-Paper-1318]
	at com.google.common.collect.ImmutableMap$Builder.put(ImmutableMap.java:248) ~[patched_1.12.2.jar:git-Paper-1318]
	at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftMetaItem.serialize(CraftMetaItem.java:898) ~[patched_1.12.2.jar:git-Paper-1318]
	at org.bukkit.util.io.Wrapper.newWrapper(Wrapper.java:17) ~[patched_1.12.2.jar:git-Paper-1318]
	at org.bukkit.util.io.BukkitObjectOutputStream.replaceObject(BukkitObjectOutputStream.java:47) ~[patched_1.12.2.jar:git-Paper-1318]
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1144) ~[?:1.8.0_162]
	at java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1378) ~[?:1.8.0_162]
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1174) ~[?:1.8.0_162]
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548) ~[?:1.8.0_162]
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509) ~[?:1.8.0_162]
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432) ~[?:1.8.0_162]
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178) ~[?:1.8.0_162]
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548) ~[?:1.8.0_162]
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509) ~[?:1.8.0_162]
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432) ~[?:1.8.0_162]
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178) ~[?:1.8.0_162]
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348) ~[?:1.8.0_162]
	at com.drtshock.playervaults.vaultmanagement.Base64Serialization.toBase64(Base64Serialization.java:29) ~[PlayerVaultsX.jar:?]
	at com.drtshock.playervaults.vaultmanagement.VaultManager.saveVault(VaultManager.java:42) ~[PlayerVaultsX.jar:?]
	at com.drtshock.playervaults.listeners.Listeners.saveVault(Listeners.java:59) ~[PlayerVaultsX.jar:?]
	at com.drtshock.playervaults.listeners.Listeners.onClose(Listeners.java:94) ~[PlayerVaultsX.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor254.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1318]
	... 17 more
```

**Comment by mibby** [comment]
@drtshock Lots of different players reporting loss of their PVs due to the same error. :(

```
[15:20:59] [Server thread/ERROR]: Could not pass event InventoryCloseEvent to PlayerVaults v4.0.2-SNAPSHOT
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1320]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1320]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1320]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) ~[patched_1.12.2.jar:git-Paper-1320]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) ~[patched_1.12.2.jar:git-Paper-1320]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:932) ~[patched_1.12.2.jar:git-Paper-1320]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1761) ~[patched_1.12.2.jar:git-Paper-1320]
	at net.minecraft.server.v1_12_R1.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:18) ~[patched_1.12.2.jar:git-Paper-1320]
	at net.minecraft.server.v1_12_R1.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:5) ~[patched_1.12.2.jar:git-Paper-1320]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1320]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_162]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_162]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.2.jar:git-Paper-1320]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [patched_1.12.2.jar:git-Paper-1320]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1320]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1320]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1320]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
Caused by: java.lang.IllegalStateException: Cannot into itemstacksz!
	at com.drtshock.playervaults.vaultmanagement.Base64Serialization.toBase64(Base64Serialization.java:36) ~[PlayerVaultsX.jar:?]
	at com.drtshock.playervaults.vaultmanagement.VaultManager.saveVault(VaultManager.java:42) ~[PlayerVaultsX.jar:?]
	at com.drtshock.playervaults.listeners.Listeners.saveVault(Listeners.java:59) ~[PlayerVaultsX.jar:?]
	at com.drtshock.playervaults.listeners.Listeners.onClose(Listeners.java:94) ~[PlayerVaultsX.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor254.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1320]
	... 17 more
Caused by: java.lang.NullPointerException: null value in entry: meta-type=null
	at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:34) ~[patched_1.12.2.jar:git-Paper-1320]
	at com.google.common.collect.ImmutableMapEntry.<init>(ImmutableMapEntry.java:49) ~[patched_1.12.2.jar:git-Paper-1320]
	at com.google.common.collect.ImmutableMap.entryOf(ImmutableMap.java:172) ~[patched_1.12.2.jar:git-Paper-1320]
	at com.google.common.collect.ImmutableMap$Builder.put(ImmutableMap.java:248) ~[patched_1.12.2.jar:git-Paper-1320]
	at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftMetaItem.serialize(CraftMetaItem.java:898) ~[patched_1.12.2.jar:git-Paper-1320]
	at org.bukkit.util.io.Wrapper.newWrapper(Wrapper.java:17) ~[patched_1.12.2.jar:git-Paper-1320]
	at org.bukkit.util.io.BukkitObjectOutputStream.replaceObject(BukkitObjectOutputStream.java:47) ~[patched_1.12.2.jar:git-Paper-1320]
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1144) ~[?:1.8.0_162]
	at java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1378) ~[?:1.8.0_162]
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1174) ~[?:1.8.0_162]
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548) ~[?:1.8.0_162]
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509) ~[?:1.8.0_162]
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432) ~[?:1.8.0_162]
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178) ~[?:1.8.0_162]
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548) ~[?:1.8.0_162]
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509) ~[?:1.8.0_162]
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432) ~[?:1.8.0_162]
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178) ~[?:1.8.0_162]
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348) ~[?:1.8.0_162]
	at com.drtshock.playervaults.vaultmanagement.Base64Serialization.toBase64(Base64Serialization.java:29) ~[PlayerVaultsX.jar:?]
	at com.drtshock.playervaults.vaultmanagement.VaultManager.saveVault(VaultManager.java:42) ~[PlayerVaultsX.jar:?]
	at com.drtshock.playervaults.listeners.Listeners.saveVault(Listeners.java:59) ~[PlayerVaultsX.jar:?]
	at com.drtshock.playervaults.listeners.Listeners.onClose(Listeners.java:94) ~[PlayerVaultsX.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor254.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1320]
	... 17 more
```

---

```
[19:09:11] [Server thread/ERROR]: Could not pass event InventoryCloseEvent to PlayerVaults v4.0.2-SNAPSHOT
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1320]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1320]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1320]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) ~[patched_1.12.2.jar:git-Paper-1320]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) ~[patched_1.12.2.jar:git-Paper-1320]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:932) ~[patched_1.12.2.jar:git-Paper-1320]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1761) ~[patched_1.12.2.jar:git-Paper-1320]
	at net.minecraft.server.v1_12_R1.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:18) ~[patched_1.12.2.jar:git-Paper-1320]
	at net.minecraft.server.v1_12_R1.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:5) ~[patched_1.12.2.jar:git-Paper-1320]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1320]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_162]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_162]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.2.jar:git-Paper-1320]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [patched_1.12.2.jar:git-Paper-1320]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1320]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1320]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1320]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
Caused by: java.lang.IllegalStateException: Cannot into itemstacksz!
	at com.drtshock.playervaults.vaultmanagement.Base64Serialization.toBase64(Base64Serialization.java:36) ~[PlayerVaultsX.jar:?]
	at com.drtshock.playervaults.vaultmanagement.VaultManager.saveVault(VaultManager.java:42) ~[PlayerVaultsX.jar:?]
	at com.drtshock.playervaults.listeners.Listeners.saveVault(Listeners.java:59) ~[PlayerVaultsX.jar:?]
	at com.drtshock.playervaults.listeners.Listeners.onClose(Listeners.java:94) ~[PlayerVaultsX.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor254.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1320]
	... 17 more
Caused by: java.lang.NullPointerException: null value in entry: meta-type=null
	at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:34) ~[patched_1.12.2.jar:git-Paper-1320]
	at com.google.common.collect.ImmutableMapEntry.<init>(ImmutableMapEntry.java:49) ~[patched_1.12.2.jar:git-Paper-1320]
	at com.google.common.collect.ImmutableMap.entryOf(ImmutableMap.java:172) ~[patched_1.12.2.jar:git-Paper-1320]
	at com.google.common.collect.ImmutableMap$Builder.put(ImmutableMap.java:248) ~[patched_1.12.2.jar:git-Paper-1320]
	at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftMetaItem.serialize(CraftMetaItem.java:898) ~[patched_1.12.2.jar:git-Paper-1320]
	at org.bukkit.util.io.Wrapper.newWrapper(Wrapper.java:17) ~[patched_1.12.2.jar:git-Paper-1320]
	at org.bukkit.util.io.BukkitObjectOutputStream.replaceObject(BukkitObjectOutputStream.java:47) ~[patched_1.12.2.jar:git-Paper-1320]
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1144) ~[?:1.8.0_162]
	at java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1378) ~[?:1.8.0_162]
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1174) ~[?:1.8.0_162]
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548) ~[?:1.8.0_162]
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509) ~[?:1.8.0_162]
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432) ~[?:1.8.0_162]
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178) ~[?:1.8.0_162]
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548) ~[?:1.8.0_162]
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509) ~[?:1.8.0_162]
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432) ~[?:1.8.0_162]
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178) ~[?:1.8.0_162]
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348) ~[?:1.8.0_162]
	at com.drtshock.playervaults.vaultmanagement.Base64Serialization.toBase64(Base64Serialization.java:29) ~[PlayerVaultsX.jar:?]
	at com.drtshock.playervaults.vaultmanagement.VaultManager.saveVault(VaultManager.java:42) ~[PlayerVaultsX.jar:?]
	at com.drtshock.playervaults.listeners.Listeners.saveVault(Listeners.java:59) ~[PlayerVaultsX.jar:?]
	at com.drtshock.playervaults.listeners.Listeners.onClose(Listeners.java:94) ~[PlayerVaultsX.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor254.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1320]
	... 17 more
```

---
```
[00:41:18] [Server thread/ERROR]: Could not pass event InventoryCloseEvent to PlayerVaults v4.0.2-SNAPSHOT
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1320]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1320]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1320]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) ~[patched_1.12.2.jar:git-Paper-1320]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) ~[patched_1.12.2.jar:git-Paper-1320]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:932) ~[patched_1.12.2.jar:git-Paper-1320]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1761) ~[patched_1.12.2.jar:git-Paper-1320]
	at net.minecraft.server.v1_12_R1.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:18) ~[patched_1.12.2.jar:git-Paper-1320]
	at net.minecraft.server.v1_12_R1.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:5) ~[patched_1.12.2.jar:git-Paper-1320]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1320]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_162]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_162]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.2.jar:git-Paper-1320]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [patched_1.12.2.jar:git-Paper-1320]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1320]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1320]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1320]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
Caused by: java.lang.IllegalStateException: Cannot into itemstacksz!
	at com.drtshock.playervaults.vaultmanagement.Base64Serialization.toBase64(Base64Serialization.java:36) ~[PlayerVaultsX.jar:?]
	at com.drtshock.playervaults.vaultmanagement.VaultManager.saveVault(VaultManager.java:42) ~[PlayerVaultsX.jar:?]
	at com.drtshock.playervaults.listeners.Listeners.saveVault(Listeners.java:59) ~[PlayerVaultsX.jar:?]
	at com.drtshock.playervaults.listeners.Listeners.onClose(Listeners.java:94) ~[PlayerVaultsX.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor254.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1320]
	... 17 more
Caused by: java.lang.NullPointerException: null value in entry: meta-type=null
	at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:34) ~[patched_1.12.2.jar:git-Paper-1320]
	at com.google.common.collect.ImmutableMapEntry.<init>(ImmutableMapEntry.java:49) ~[patched_1.12.2.jar:git-Paper-1320]
	at com.google.common.collect.ImmutableMap.entryOf(ImmutableMap.java:172) ~[patched_1.12.2.jar:git-Paper-1320]
	at com.google.common.collect.ImmutableMap$Builder.put(ImmutableMap.java:248) ~[patched_1.12.2.jar:git-Paper-1320]
	at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftMetaItem.serialize(CraftMetaItem.java:898) ~[patched_1.12.2.jar:git-Paper-1320]
	at org.bukkit.util.io.Wrapper.newWrapper(Wrapper.java:17) ~[patched_1.12.2.jar:git-Paper-1320]
	at org.bukkit.util.io.BukkitObjectOutputStream.replaceObject(BukkitObjectOutputStream.java:47) ~[patched_1.12.2.jar:git-Paper-1320]
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1144) ~[?:1.8.0_162]
	at java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1378) ~[?:1.8.0_162]
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1174) ~[?:1.8.0_162]
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548) ~[?:1.8.0_162]
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509) ~[?:1.8.0_162]
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432) ~[?:1.8.0_162]
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178) ~[?:1.8.0_162]
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548) ~[?:1.8.0_162]
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509) ~[?:1.8.0_162]
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432) ~[?:1.8.0_162]
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178) ~[?:1.8.0_162]
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348) ~[?:1.8.0_162]
	at com.drtshock.playervaults.vaultmanagement.Base64Serialization.toBase64(Base64Serialization.java:29) ~[PlayerVaultsX.jar:?]
	at com.drtshock.playervaults.vaultmanagement.VaultManager.saveVault(VaultManager.java:42) ~[PlayerVaultsX.jar:?]
	at com.drtshock.playervaults.listeners.Listeners.saveVault(Listeners.java:59) ~[PlayerVaultsX.jar:?]
	at com.drtshock.playervaults.listeners.Listeners.onClose(Listeners.java:94) ~[PlayerVaultsX.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor254.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1320]
	... 17 more

```

**Comment by drtshock** [comment]
Should be fixed in latest release.
