### ISSUE TITLE
Error on PV

### ISSUE THREAD

**Issue by xKenn12** [drtshock/PlayerVaults#390]
[ERROR] Could not pass event InventoryClickEvent to PlayerVaults v3.5.7-b${BUILD_NUMBER}

org.bukkit.event.EventException

at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:297) ~[craftbukkit-1.8.jar:git-Bukkit-7019900]

at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit-1.8.jar:git-Bukkit-7019900]

at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [craftbukkit-1.8.jar:git-Bukkit-7019900]

at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [craftbukkit-1.8.jar:git-Bukkit-7019900]

at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:1521) [craftbukkit-1.8.jar:git-Bukkit-7019900]

at net.minecraft.server.v1_8_R1.PacketPlayInWindowClick.a(SourceFile:31) [craftbukkit-1.8.jar:git-Bukkit-7019900]

at net.minecraft.server.v1_8_R1.PacketPlayInWindowClick.a(SourceFile:9) [craftbukkit-1.8.jar:git-Bukkit-7019900]

at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [craftbukkit-1.8.jar:git-Bukkit-7019900]

at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]

at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]

at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:656) [craftbukkit-1.8.jar:git-Bukkit-7019900]

at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:284) [craftbukkit-1.8.jar:git-Bukkit-7019900]

at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:609) [craftbukkit-1.8.jar:git-Bukkit-7019900]

at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:517) [craftbukkit-1.8.jar:git-Bukkit-7019900]

at java.lang.Thread.run(Thread.java:813) [?:1.8.0_212]

Caused by: java.lang.NoSuchMethodError: org/bukkit/event/inventory/InventoryClickEvent.getClickedInventory()Lorg/bukkit/inventory/Inventory; (loaded from file:/pro/bin/mc/craftbukkit/1.8/craftbukkit-1.8.jar by sun.misc.Launcher$AppClassLoader@5b57a7e5) called from class com.drtshock.playervaults.listeners.Listeners (loaded from file:/home/gs-41489/plugins/PlayerVaults.jar by org.bukkit.plugin.java.PluginClassLoader@6adfe0da).

at com.drtshock.playervaults.listeners.Listeners.onClick(Listeners.java:121) ~[?:?]

at sun.reflect.GeneratedMethodAccessor112.invoke(Unknown Source) ~[?:?]

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]

at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]

at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:295) ~[craftbukkit-1.8.jar:git-Bukkit-7019900]

... 14 more

how could i fix this issue in my console?

**Comment by SurvivalQuest** [comment]
Same issue here but with PV 4.1.2 and PaperMC 1.14.3
https://pastebin.com/7qY8Xzjy

**Comment by kashike** [comment]
Use a modern version of the game.

@SurvivalQuest That is not the same issue.
