### ISSUE TITLE
1.14.3 [07/01/2019 08:37:41 pm] [ERROR]: Could not pass event InventoryClickEvent to PlayerVaults v4.1.2

### ISSUE THREAD

**Issue by 151baccardi** [drtshock/PlayerVaults#391]
### PlayerVaultsX Version
*Run `/version playervaults` and give us your output.* 

### Server Version
*Run `/version` and give us your output.*

### Logs
*Give use your logs by going to `logs/latest.log`.*

### Details
*Please explain the problem.*

**Comment by 151baccardi** [comment]
PlayerVaults version 4.1.2[07/01/2019 08:43:33 pm] [INFO]: Website: https://www.spigotmc.org/resources/51204/[07/01/2019 08:43:33 pm] [INFO]: Authors: drtshock and kashike

The problem is massive spam of the likes of messages posted below.


[00:37:40] [Server thread/ERROR]: Could not pass event InventoryClickEvent to PlayerVaults v4.1.2
java.lang.NullPointerException: null
	at com.drtshock.playervaults.listeners.Listeners.onClick(Listeners.java:122) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor437.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[b112.jar:git-Paper-112]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[b112.jar:git-Paper-112]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[b112.jar:git-Paper-112]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:536) ~[b112.jar:git-Paper-112]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2341) ~[b112.jar:git-Paper-112]
	at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[b112.jar:git-Paper-112]
	at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[b112.jar:git-Paper-112]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18) ~[b112.jar:git-Paper-112]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[b112.jar:git-Paper-112]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127) ~[b112.jar:git-Paper-112]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[b112.jar:git-Paper-112]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105) ~[b112.jar:git-Paper-112]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:1002) ~[b112.jar:git-Paper-112]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:995) ~[b112.jar:git-Paper-112]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:91) ~[b112.jar:git-Paper-112]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:978) ~[b112.jar:git-Paper-112]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:912) ~[b112.jar:git-Paper-112]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[00:37:40] [Server thread/ERROR]: Could not pass event InventoryClickEvent to PlayerVaults v4.1.2
java.lang.NullPointerException: null
	at com.drtshock.playervaults.listeners.Listeners.onClick(Listeners.java:122) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor437.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[b112.jar:git-Paper-112]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[b112.jar:git-Paper-112]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[b112.jar:git-Paper-112]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:536) ~[b112.jar:git-Paper-112]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2341) ~[b112.jar:git-Paper-112]
	at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[b112.jar:git-Paper-112]
	at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[b112.jar:git-Paper-112]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18) ~[b112.jar:git-Paper-112]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[b112.jar:git-Paper-112]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127) ~[b112.jar:git-Paper-112]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[b112.jar:git-Paper-112]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105) ~[b112.jar:git-Paper-112]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:1002) ~[b112.jar:git-Paper-112]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:995) ~[b112.jar:git-Paper-112]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:115) ~[b112.jar:git-Paper-112]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:979) ~[b112.jar:git-Paper-112]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:912) ~[b112.jar:git-Paper-112]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[00:37:41] [Server thread/ERROR]: Could not pass event InventoryClickEvent to PlayerVaults v4.1.2
java.lang.NullPointerException: null
	at com.drtshock.playervaults.listeners.Listeners.onClick(Listeners.java:122) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor437.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[b112.jar:git-Paper-112]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[b112.jar:git-Paper-112]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[b112.jar:git-Paper-112]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:536) ~[b112.jar:git-Paper-112]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2341) ~[b112.jar:git-Paper-112]
	at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[b112.jar:git-Paper-112]
	at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[b112.jar:git-Paper-112]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18) ~[b112.jar:git-Paper-112]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[b112.jar:git-Paper-112]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127) ~[b112.jar:git-Paper-112]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[b112.jar:git-Paper-112]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105) ~[b112.jar:git-Paper-112]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:1002) ~[b112.jar:git-Paper-112]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:995) ~[b112.jar:git-Paper-112]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:91) ~[b112.jar:git-Paper-112]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:978) ~[b112.jar:git-Paper-112]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:912) ~[b112.jar:git-Paper-112]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[00:37:59] [Server thread/INFO]: BlueDoes2 issued server command: /pv 2

**Comment by ArtelGG** [comment]
Update to the latest development build found [here](https://ci.ender.zone/job/PlayerVaultsX/lastStableBuild).
