### ISSUE TITLE
NoClassDefFoundError: com/drtshock/playervaults/lib/net/kyori/adventure/sound/Sound$Emitter

### ISSUE THREAD

**Issue by mibby** [drtshock/PlayerVaults#434]
### PlayerVaultsX Version
PlayerVaults version 4.2.0 dev 26

### Server Version
Paper version git-Paper-68 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: f18dc1e)

### Logs
```
[10:44:04] [Server thread/INFO]: [PlayerVaults] Enabling PlayerVaults v4.2.0
[10:44:04] [Server thread/ERROR]: Error occurred while enabling PlayerVaults v4.2.0 (Is it up to date?)
java.lang.NoClassDefFoundError: com/drtshock/playervaults/lib/net/kyori/adventure/sound/Sound$Emitter
	at com.drtshock.playervaults.PlayerVaults.onEnable(PlayerVaults.java:120) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.jar:git-Paper-68]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.jar:git-Paper-68]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.jar:git-Paper-68]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.17.jar:git-Paper-68]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.17.jar:git-Paper-68]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:643) ~[patched_1.17.jar:git-Paper-68]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:304) ~[patched_1.17.jar:git-Paper-68]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1118) ~[patched_1.17.jar:git-Paper-68]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-68]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: com.drtshock.playervaults.lib.net.kyori.adventure.sound.Sound$Emitter
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:146) ~[patched_1.17.jar:git-Paper-68]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[patched_1.17.jar:git-Paper-68]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	... 11 more
```

### Details
Error at start-up initialization. Breaking changes with latest source commits or Paper 1.17?

**Comment by mbax** [comment]
Try the build on spigot and let me know if it works

**Comment by mibby** [comment]
Spigot build seems to work so I suppose it's just https://ci.ender.zone/ build server breaking compilation. Can probably ignore and close this since official premium builds are fine. Thanks!

**Comment by mbax** [comment]
Thanks, mibby. I'll look into it because obviously the message is not a good sign overall :D
