### ISSUE TITLE
[Error] Could not call method 'public static org.bukkit.inventory.meta.ItemMeta 

### ISSUE THREAD

**Issue by mibby** [drtshock/PlayerVaults#48]
http://ci.drtshock.net/job/PlayerVaults/157/

Opened someone's player vault with the command '/pv [player] 1'. This error spammed in console.
http://paste.ubuntu.com/8586150/

```
[23:09:55] [Server thread/ERROR]: Could not call method 'public static org.bukkit.inventory.meta.ItemMeta org.bukkit.craftbukkit.v1_7_R4.inventory.CraftMetaItem$SerializableMeta.deserialize(java.util.Map) throws java.lang.Throwable' of class org.bukkit.craftbukkit.v1_7_R4.inventory.CraftMetaItem$SerializableMeta for deserialization
java.lang.IllegalArgumentException: BOOK is not a valid meta-type
	at org.bukkit.craftbukkit.v1_7_R4.inventory.CraftMetaItem$SerializableMeta.deserialize(CraftMetaItem.java:137) ~[spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:73) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:113) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:191) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at com.drtshock.playervaults.vaultmanagement.Serialization.deserialize(Serialization.java:153) [PlayerVaults.jar:?]
	at com.drtshock.playervaults.vaultmanagement.Serialization.deserialize(Serialization.java:148) [PlayerVaults.jar:?]
	at com.drtshock.playervaults.vaultmanagement.Serialization.toInventory(Serialization.java:94) [PlayerVaults.jar:?]
	at com.drtshock.playervaults.vaultmanagement.UUIDVaultManager.getInventory(UUIDVaultManager.java:149) [PlayerVaults.jar:?]
	at com.drtshock.playervaults.vaultmanagement.UUIDVaultManager.loadOtherVault(UUIDVaultManager.java:119) [PlayerVaults.jar:?]
	at com.drtshock.playervaults.vaultmanagement.VaultOperations.openOtherVault(VaultOperations.java:163) [PlayerVaults.jar:?]
	at com.drtshock.playervaults.commands.VaultCommand.onCommand(VaultCommand.java:63) [PlayerVaults.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:767) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.PlayerConnection.handleCommand(PlayerConnection.java:1043) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:880) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.PacketPlayInChat.a(PacketPlayInChat.java:28) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.PacketPlayInChat.handle(PacketPlayInChat.java:65) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:186) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
[23:09:55] [Server thread/ERROR]: Could not call method 'public static org.bukkit.inventory.meta.ItemMeta org.bukkit.craftbukkit.v1_7_R4.inventory.CraftMetaItem$SerializableMeta.deserialize(java.util.Map) throws java.lang.Throwable' of class org.bukkit.craftbukkit.v1_7_R4.inventory.CraftMetaItem$SerializableMeta for deserialization
java.lang.IllegalArgumentException: BOOK is not a valid meta-type
	at org.bukkit.craftbukkit.v1_7_R4.inventory.CraftMetaItem$SerializableMeta.deserialize(CraftMetaItem.java:137) ~[spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:73) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:113) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:191) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at com.drtshock.playervaults.vaultmanagement.Serialization.deserialize(Serialization.java:153) [PlayerVaults.jar:?]
	at com.drtshock.playervaults.vaultmanagement.Serialization.deserialize(Serialization.java:148) [PlayerVaults.jar:?]
	at com.drtshock.playervaults.vaultmanagement.Serialization.toInventory(Serialization.java:94) [PlayerVaults.jar:?]
	at com.drtshock.playervaults.vaultmanagement.UUIDVaultManager.getInventory(UUIDVaultManager.java:149) [PlayerVaults.jar:?]
	at com.drtshock.playervaults.vaultmanagement.UUIDVaultManager.loadOtherVault(UUIDVaultManager.java:119) [PlayerVaults.jar:?]
	at com.drtshock.playervaults.vaultmanagement.VaultOperations.openOtherVault(VaultOperations.java:163) [PlayerVaults.jar:?]
	at com.drtshock.playervaults.commands.VaultCommand.onCommand(VaultCommand.java:63) [PlayerVaults.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:767) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.PlayerConnection.handleCommand(PlayerConnection.java:1043) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:880) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.PacketPlayInChat.a(PacketPlayInChat.java:28) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.PacketPlayInChat.handle(PacketPlayInChat.java:65) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:186) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
[23:09:55] [Server thread/ERROR]: Could not call method 'public static org.bukkit.inventory.meta.ItemMeta org.bukkit.craftbukkit.v1_7_R4.inventory.CraftMetaItem$SerializableMeta.deserialize(java.util.Map) throws java.lang.Throwable' of class org.bukkit.craftbukkit.v1_7_R4.inventory.CraftMetaItem$SerializableMeta for deserialization
java.lang.IllegalArgumentException: BOOK is not a valid meta-type
	at org.bukkit.craftbukkit.v1_7_R4.inventory.CraftMetaItem$SerializableMeta.deserialize(CraftMetaItem.java:137) ~[spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:73) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:113) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:191) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at com.drtshock.playervaults.vaultmanagement.Serialization.deserialize(Serialization.java:153) [PlayerVaults.jar:?]
	at com.drtshock.playervaults.vaultmanagement.Serialization.deserialize(Serialization.java:148) [PlayerVaults.jar:?]
	at com.drtshock.playervaults.vaultmanagement.Serialization.toInventory(Serialization.java:94) [PlayerVaults.jar:?]
	at com.drtshock.playervaults.vaultmanagement.UUIDVaultManager.getInventory(UUIDVaultManager.java:149) [PlayerVaults.jar:?]
	at com.drtshock.playervaults.vaultmanagement.UUIDVaultManager.loadOtherVault(UUIDVaultManager.java:122) [PlayerVaults.jar:?]
	at com.drtshock.playervaults.vaultmanagement.VaultOperations.openOtherVault(VaultOperations.java:163) [PlayerVaults.jar:?]
	at com.drtshock.playervaults.commands.VaultCommand.onCommand(VaultCommand.java:63) [PlayerVaults.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:767) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.PlayerConnection.handleCommand(PlayerConnection.java:1043) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:880) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.PacketPlayInChat.a(PacketPlayInChat.java:28) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.PacketPlayInChat.handle(PacketPlayInChat.java:65) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:186) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
[23:09:55] [Server thread/ERROR]: Could not call method 'public static org.bukkit.inventory.meta.ItemMeta org.bukkit.craftbukkit.v1_7_R4.inventory.CraftMetaItem$SerializableMeta.deserialize(java.util.Map) throws java.lang.Throwable' of class org.bukkit.craftbukkit.v1_7_R4.inventory.CraftMetaItem$SerializableMeta for deserialization
java.lang.IllegalArgumentException: BOOK is not a valid meta-type
	at org.bukkit.craftbukkit.v1_7_R4.inventory.CraftMetaItem$SerializableMeta.deserialize(CraftMetaItem.java:137) ~[spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at sun.reflect.GeneratedMethodAccessor607.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:73) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:113) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:191) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at com.drtshock.playervaults.vaultmanagement.Serialization.deserialize(Serialization.java:153) [PlayerVaults.jar:?]
	at com.drtshock.playervaults.vaultmanagement.Serialization.deserialize(Serialization.java:148) [PlayerVaults.jar:?]
	at com.drtshock.playervaults.vaultmanagement.Serialization.toInventory(Serialization.java:94) [PlayerVaults.jar:?]
	at com.drtshock.playervaults.vaultmanagement.UUIDVaultManager.getInventory(UUIDVaultManager.java:149) [PlayerVaults.jar:?]
	at com.drtshock.playervaults.vaultmanagement.UUIDVaultManager.loadOtherVault(UUIDVaultManager.java:122) [PlayerVaults.jar:?]
	at com.drtshock.playervaults.vaultmanagement.VaultOperations.openOtherVault(VaultOperations.java:163) [PlayerVaults.jar:?]
	at com.drtshock.playervaults.commands.VaultCommand.onCommand(VaultCommand.java:63) [PlayerVaults.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:767) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.PlayerConnection.handleCommand(PlayerConnection.java:1043) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:880) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.PacketPlayInChat.a(PacketPlayInChat.java:28) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.PacketPlayInChat.handle(PacketPlayInChat.java:65) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:186) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
```

**Comment by drtshock** [comment]
Can you confirm this on Spigot 1.8 or newer?
