### ISSUE TITLE
Could not pass event InventoryClickEvent to PlayerVaults v3.5.4-SNAPSHOT

### ISSUE THREAD

**Issue by mibby** [drtshock/PlayerVaults#73]
PlayerVaults dev 170
Spigot 1.8.5 git-Spigot-17fce80-529e4cd

```
[23:08:51] [Server thread/ERROR]: Could not pass event InventoryClickEvent to PlayerVaults v3.5.4-SNAPSHOT
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-17fce80-529e4cd]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-17fce80-529e4cd]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-17fce80-529e4cd]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-17fce80-529e4cd]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1603) [spigot.jar:git-Spigot-17fce80-529e4cd]
	at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31) [spigot.jar:git-Spigot-17fce80-529e4cd]
	at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9) [spigot.jar:git-Spigot-17fce80-529e4cd]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-17fce80-529e4cd]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:60) [spigot.jar:git-Spigot-17fce80-529e4cd]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:718) [spigot.jar:git-Spigot-17fce80-529e4cd]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:368) [spigot.jar:git-Spigot-17fce80-529e4cd]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot.jar:git-Spigot-17fce80-529e4cd]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot.jar:git-Spigot-17fce80-529e4cd]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.NullPointerException
	at com.drtshock.playervaults.listeners.Listeners.onClick(Listeners.java:247) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor337.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-17fce80-529e4cd]
	... 15 more
```

**Comment by drtshock** [comment]
What causes this to show up?

**Comment by mibby** [comment]
I'm assuming people opening their vault and clicking around / dragging items? Other than that, not sure. Only noticed it from console a few times.

**Comment by TWSSYesterday** [comment]
Also having this on latest version.

**Comment by mibby** [comment]
For what it's worth, still occurs on Spigot 1.8.7 git-Spigot-07a5b1b-04afd79 and PlayerVaults dev 171.

```
[05:50:47] [Server thread/ERROR]: Could not pass event InventoryClickEvent to PlayerVaults v3.5.5-SNAPSHOT
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-07a5b1b-04afd79]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-07a5b1b-04afd79]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-07a5b1b-04afd79]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-07a5b1b-04afd79]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1603) [spigot.jar:git-Spigot-07a5b1b-04afd79]
	at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31) [spigot.jar:git-Spigot-07a5b1b-04afd79]
	at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9) [spigot.jar:git-Spigot-07a5b1b-04afd79]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-07a5b1b-04afd79]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) [spigot.jar:git-Spigot-07a5b1b-04afd79]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:718) [spigot.jar:git-Spigot-07a5b1b-04afd79]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [spigot.jar:git-Spigot-07a5b1b-04afd79]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot.jar:git-Spigot-07a5b1b-04afd79]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot.jar:git-Spigot-07a5b1b-04afd79]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.NullPointerException
	at com.drtshock.playervaults.listeners.Listeners.onClick(Listeners.java:259) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor291.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-07a5b1b-04afd79]
	... 15 more
```

**Comment by drtshock** [comment]
Can you tell me how to make this error show up?

**Comment by mibby** [comment]
As mentioned above, I'm not entirely sure. I only see it in console / server logs. I presume it occurs when players click around inside their vault - drag items in and out or click around.

**Comment by mibby** [comment]
@drtshock @kashike Commit https://github.com/drtshock/PlayerVaults/commit/c2fa317e169ca4221b3646e952d1c2112d0b78da didn't seem to fix the issue. Still see the error dozens of times in the server log.

Spigot 1.8.7 git-Spigot-44c59bf-8f0f4ed
PlayerVaults dev 172
```
[13:22:23] [Server thread/ERROR]: Could not pass event InventoryClickEvent to PlayerVaults v3.5.5-SNAPSHOT
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-44c59bf-8f0f4ed]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-44c59bf-8f0f4ed]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-44c59bf-8f0f4ed]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-44c59bf-8f0f4ed]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1603) [spigot.jar:git-Spigot-44c59bf-8f0f4ed]
	at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31) [spigot.jar:git-Spigot-44c59bf-8f0f4ed]
	at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9) [spigot.jar:git-Spigot-44c59bf-8f0f4ed]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-44c59bf-8f0f4ed]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) [spigot.jar:git-Spigot-44c59bf-8f0f4ed]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:718) [spigot.jar:git-Spigot-44c59bf-8f0f4ed]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [spigot.jar:git-Spigot-44c59bf-8f0f4ed]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot.jar:git-Spigot-44c59bf-8f0f4ed]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot.jar:git-Spigot-44c59bf-8f0f4ed]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.NullPointerException
	at com.drtshock.playervaults.listeners.Listeners.onClick(Listeners.java:259) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor304.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-44c59bf-8f0f4ed]
	... 15 more
[13:22:24] [Server thread/ERROR]: Could not pass event InventoryClickEvent to PlayerVaults v3.5.5-SNAPSHOT
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-44c59bf-8f0f4ed]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-44c59bf-8f0f4ed]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-44c59bf-8f0f4ed]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-44c59bf-8f0f4ed]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1603) [spigot.jar:git-Spigot-44c59bf-8f0f4ed]
	at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31) [spigot.jar:git-Spigot-44c59bf-8f0f4ed]
	at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9) [spigot.jar:git-Spigot-44c59bf-8f0f4ed]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-44c59bf-8f0f4ed]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) [spigot.jar:git-Spigot-44c59bf-8f0f4ed]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:718) [spigot.jar:git-Spigot-44c59bf-8f0f4ed]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [spigot.jar:git-Spigot-44c59bf-8f0f4ed]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot.jar:git-Spigot-44c59bf-8f0f4ed]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot.jar:git-Spigot-44c59bf-8f0f4ed]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.NullPointerException
	at com.drtshock.playervaults.listeners.Listeners.onClick(Listeners.java:259) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor304.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-44c59bf-8f0f4ed]
	... 15 more
[13:22:25] [Server thread/ERROR]: Could not pass event InventoryClickEvent to PlayerVaults v3.5.5-SNAPSHOT
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-44c59bf-8f0f4ed]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-44c59bf-8f0f4ed]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-44c59bf-8f0f4ed]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-44c59bf-8f0f4ed]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1603) [spigot.jar:git-Spigot-44c59bf-8f0f4ed]
	at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31) [spigot.jar:git-Spigot-44c59bf-8f0f4ed]
	at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9) [spigot.jar:git-Spigot-44c59bf-8f0f4ed]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-44c59bf-8f0f4ed]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) [spigot.jar:git-Spigot-44c59bf-8f0f4ed]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:718) [spigot.jar:git-Spigot-44c59bf-8f0f4ed]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [spigot.jar:git-Spigot-44c59bf-8f0f4ed]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot.jar:git-Spigot-44c59bf-8f0f4ed]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot.jar:git-Spigot-44c59bf-8f0f4ed]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.NullPointerException
	at com.drtshock.playervaults.listeners.Listeners.onClick(Listeners.java:259) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor304.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-44c59bf-8f0f4ed]
	... 15 more
```

**Comment by mibby** [comment]
Any update to what may be causing this error?

**Comment by mibby** [comment]
@drtshock @kashike The InventoryClickEvent exception began with dev build 170. Could it be related to this commit, which imports the InventoryClickEvent?

https://github.com/drtshock/PlayerVaults/commit/24f423d2f312c0c4856e70f70f0b5981f8dddd21#diff-fa9ec9c8a4247f7c6d305ad16fdadfd7R38

**Comment by drtshock** [comment]
Yes but I need to know how to reproduce it.

**Comment by mibby** [comment]
Sorry, I'm at a loss for how to reproduce. I tried myself numerous times to see if I can get the error to reoccur, but I can't. The only thing I'm able to reproduce is when using a build containing the commit that utilizes the InventoryClickEvent, errors are present in the server log. With a build that does not contain the commit (dev 169), no errors are present.

Might be best to inquire to the two people in this ticket who also seem to get the error.
https://github.com/drtshock/PlayerVaults/issues/76

**Comment by mibby** [comment]
@drtshock The revert doesn't fix the issue. That commit was an attempt to resolve the error, which it didn't fix. 

The error still occurs due to this commit.
https://github.com/drtshock/PlayerVaults/commit/24f423d2f312c0c4856e70f70f0b5981f8dddd21#diff-fa9ec9c8a4247f7c6d305ad16fdadfd7R38

Any builds not containing that commit, there is no error.

**Comment by drtshock** [comment]
Can you please tell me how to reproduce.

**Comment by mibby** [comment]
4th time saying this, I'm not sure how to reproduce. All I've been able to discern is the error occurs in my logs with any build containing the commit I linked. Using a build without that commit, I don't have that error.

And again stating this, you'd be better off asking the other people who also reported this error here https://github.com/drtshock/PlayerVaults/issues/76 to see if they may know how to reproduce. Closing the ticket without confirming and stating it is fixed without providing an actual fix isn't right.

**Comment by TWSSYesterday** [comment]
I don't get the error on 1.8.7 if that helps.

**Comment by mibby** [comment]
Again to clarify, you need to use a build that contains this commit.
https://github.com/drtshock/PlayerVaults/commit/24f423d2f312c0c4856e70f70f0b5981f8dddd21

Any version higher than dev build 169.
http://ci.drtshock.net/job/PlayerVaults/changes

**Comment by mibby** [comment]
Still not fixed as of dev build 177.

```
[13:34:59] [Server thread/ERROR]: Could not pass event InventoryClickEvent to PlayerVaults v3.5.6-SNAPSHOT
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-f928e7a-d432434]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-f928e7a-d432434]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-f928e7a-d432434]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-f928e7a-d432434]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1603) [spigot.jar:git-Spigot-f928e7a-d432434]
	at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31) [spigot.jar:git-Spigot-f928e7a-d432434]
	at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9) [spigot.jar:git-Spigot-f928e7a-d432434]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-f928e7a-d432434]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) [spigot.jar:git-Spigot-f928e7a-d432434]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:718) [spigot.jar:git-Spigot-f928e7a-d432434]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [spigot.jar:git-Spigot-f928e7a-d432434]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot.jar:git-Spigot-f928e7a-d432434]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot.jar:git-Spigot-f928e7a-d432434]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.NullPointerException
	at com.drtshock.playervaults.listeners.Listeners.onClick(Listeners.java:247) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor367.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-f928e7a-d432434]
	... 15 more
```

**Comment by kashike** [comment]
@mibby https://github.com/drtshock/PlayerVaults/commit/8980bc5facde9ad1fd0e205b067153daa623f326

**Comment by mibby** [comment]
Seems to be fixed now. Thanks.

**Comment by MiguelM200** [comment]
[22:21:15] [Server thread/ERROR]: Could not pass event InventoryClickEvent to PlayerVaults v3.6.0-bSNAPSHOT
java.lang.NoSuchMethodError: 'java.lang.String org.bukkit.inventory.Inventory.getTitle()'
	at com.drtshock.playervaults.listeners.Listeners.onClick(Listeners.java:138) ~[PlayerVaults (1).jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor275.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-388]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:669) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:2861) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1400) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1377) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1370) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1348) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-388]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
	
	Para poder reproducirlo se tiene que abrir la vault /pv 1 y introducir cualquier item y ya lanza el error en la consola

**Comment by mbax** [comment]
Upgrade to latest.
