### ISSUE TITLE
3.5.1 & 3.5.2 crash on startup

### ISSUE THREAD

**Issue by spyproof** [drtshock/PlayerVaults#75]
Hi, we are running a modded cauldron server, every time PlayerVaults starts, we get the follwoing error:

[06:56:57] [Server thread/ERROR]: Error occurred while enabling PlayerVaults v3.5.2 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.scheduler.BukkitScheduler.runTask(Lorg/bukkit/plugin/Plugin;Lorg/bukkit/scheduler/BukkitRunnable;)Lorg/bukkit/scheduler/BukkitTask;
	at com.drtshock.playervaults.PlayerVaults.onEnable(PlayerVaults.java:68) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:KCauldron-1.7.10-2.1403.1.54]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:KCauldron-1.7.10-2.1403.1.54]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:KCauldron-1.7.10-2.1403.1.54]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415) [CraftServer.class:KCauldron-1.7.10-2.1403.1.54]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349) [CraftServer.class:KCauldron-1.7.10-2.1403.1.54]
	at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:500) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:474) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:434) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:335) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:620) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]

**Comment by kashike** [comment]
Should be fixed by https://github.com/drtshock/PlayerVaults/commit/89c57dc76dd3d1b81687ac130c91895348c8c351
