### ISSUE TITLE
error

### ISSUE THREAD

**Issue by noorkoteb** [drtshock/PlayerVaults#85]
[09:34:18 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'pv' in plugin PlayerVaults v3.5.2
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[Spigot.jar:git-Spigot-c5146ba-01930e2]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[Spigot.jar:git-Spigot-c5146ba-01930e2]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:646) ~[Spigot.jar:git-Spigot-c5146ba-01930e2]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1135) [Spigot.jar:git-Spigot-c5146ba-01930e2]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:970) [Spigot.jar:git-Spigot-c5146ba-01930e2]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [Spigot.jar:git-Spigot-c5146ba-01930e2]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [Spigot.jar:git-Spigot-c5146ba-01930e2]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot.jar:git-Spigot-c5146ba-01930e2]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_79]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_79]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:60) [Spigot.jar:git-Spigot-c5146ba-01930e2]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:718) [Spigot.jar:git-Spigot-c5146ba-01930e2]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [Spigot.jar:git-Spigot-c5146ba-01930e2]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [Spigot.jar:git-Spigot-c5146ba-01930e2]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [Spigot.jar:git-Spigot-c5146ba-01930e2]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
Caused by: java.lang.NullPointerException
	at com.drtshock.playervaults.vaultmanagement.VaultOperations.getMaxVaultSize(VaultOperations.java:98) ~[?:?]
	at com.drtshock.playervaults.vaultmanagement.VaultOperations.openOtherVault(VaultOperations.java:189) ~[?:?]
	at com.drtshock.playervaults.commands.VaultCommand.onCommand(VaultCommand.java:63) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[Spigot.jar:git-Spigot-c5146ba-01930e2]
	... 15 more
>
[09:34:34 INFO]: KingPhantom_ issued server command: /pv 2
>

**Comment by noorkoteb** [comment]
i got this error when i did /pv (player that wasn't onlne) 1

**Comment by drtshock** [comment]
Use pastebin or gist please.
