### ISSUE TITLE
Issue with PvSigns

### ISSUE THREAD

**Issue by SolarShrieking** [drtshock/PlayerVaults#95]
Getting this issue when using Player Vault Signs... OP and Full perms, sometimes saying no permission. Cannot break. Some signs are breaking, not letting players access.

[13:50:08 ERROR]: Could not pass event InventoryCloseEvent to PlayerVaults v3.5.
6-b181
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:305) ~[spigot-1.8.3-2015-05-13.jar:git-Spigot-870264a-0a645a2]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:62) ~[spigot-1.8.3-2015-05-13.jar:git-Spigot-870264a-0a645a2]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j
ava:502) [spigot-1.8.3-2015-05-13.jar:git-Spigot-870264a-0a645a2]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:487) [spigot-1.8.3-2015-05-13.jar:git-Spigot-870264a-0a645a2]
        at org.bukkit.craftbukkit.v1_8_R2.event.CraftEventFactory.handleInventor
yCloseEvent(CraftEventFactory.java:838) [spigot-1.8.3-2015-05-13.jar:git-Spigot-
870264a-0a645a2]
        at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java
:1401) [spigot-1.8.3-2015-05-13.jar:git-Spigot-870264a-0a645a2]
        at net.minecraft.server.v1_8_R2.PacketPlayInCloseWindow.a(PacketPlayInCl
oseWindow.java:18) [spigot-1.8.3-2015-05-13.jar:git-Spigot-870264a-0a645a2]
        at net.minecraft.server.v1_8_R2.PacketPlayInCloseWindow.a(PacketPlayInCl
oseWindow.java:1) [spigot-1.8.3-2015-05-13.jar:git-Spigot-870264a-0a645a2]
        at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:1
3) [spigot-1.8.3-2015-05-13.jar:git-Spigot-870264a-0a645a2]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [
?:1.8.0_45]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_45]
        at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) [spigot-1.8
.3-2015-05-13.jar:git-Spigot-870264a-0a645a2]
        at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:7
12) [spigot-1.8.3-2015-05-13.jar:git-Spigot-870264a-0a645a2]
        at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:3
68) [spigot-1.8.3-2015-05-13.jar:git-Spigot-870264a-0a645a2]
        at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:6
51) [spigot-1.8.3-2015-05-13.jar:git-Spigot-870264a-0a645a2]
        at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java
:554) [spigot-1.8.3-2015-05-13.jar:git-Spigot-870264a-0a645a2]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
Caused by: java.lang.NullPointerException
>

**Comment by drtshock** [comment]
Use a paste tool like pastebin and paste the full error.

**Comment by SolarShrieking** [comment]
http://pastebin.com/VgHXjugJ

Already found a workaround, I don't need to use PVSigns anymore. Hope you can fix whatever is wrong for others, though. :P

**Comment by drtshock** [comment]
Still not the full error. I need whatever is after the last line there.

**Comment by SolarShrieking** [comment]
Woops. Just recreated it on server. Seems after I make the sign, anytime I close an inventory the error pops up until the time that I log out.  http://pastebin.com/yfi5qng6

**Comment by drtshock** [comment]
Did you reload or are you using per world plugins or something?

**Comment by SolarShrieking** [comment]
No, and no.

**Comment by CHarrisMedia** [comment]
The most irritating thing about this post is that it's a replica of mine that still has got no response.

https://github.com/drtshock/PlayerVaults/issues/93

**Comment by drtshock** [comment]
Good catch. Keep discussion on https://github.com/drtshock/PlayerVaults/issues/93
