### ISSUE TITLE
InventoryClickEvent

### ISSUE THREAD

**Issue by yarmoam233** [drtshock/PlayerVaults#98]
I'm using craftbukkit version 1.8.7-R0.1-SNAPSHOT. This error randomly occurs. I'm pretty sure I'm on the most recent version of player vaults.

[xx:xx:xx] [Server thread/ERROR]: Could not pass event InventoryClickEvent to PlayerVaults v3.5.6-b181
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[craftbukkit2.jar:git-Bukkit-d27e6d0]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit2.jar:git-Bukkit-d27e6d0]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [craftbukkit2.jar:git-Bukkit-d27e6d0]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [craftbukkit2.jar:git-Bukkit-d27e6d0]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1564) [craftbukkit2.jar:git-Bukkit-d27e6d0]
	at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31) [craftbukkit2.jar:git-Bukkit-d27e6d0]
	at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9) [craftbukkit2.jar:git-Bukkit-d27e6d0]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit2.jar:git-Bukkit-d27e6d0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_05]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_05]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) [craftbukkit2.jar:git-Bukkit-d27e6d0]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:672) [craftbukkit2.jar:git-Bukkit-d27e6d0]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:335) [craftbukkit2.jar:git-Bukkit-d27e6d0]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:628) [craftbukkit2.jar:git-Bukkit-d27e6d0]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:536) [craftbukkit2.jar:git-Bukkit-d27e6d0]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_05]
Caused by: java.lang.NoSuchMethodError: org.bukkit.event.inventory.InventoryClickEvent.getClickedInventory()Lorg/bukkit/inventory/Inventory;
	at com.drtshock.playervaults.listeners.Listeners.onClick(Listeners.java:243) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_05]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_05]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_05]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_05]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[craftbukkit2.jar:git-Bukkit-d27e6d0]
	... 15 more

**Comment by z1haze** [comment]
I also have a similar if not the same error using plugin version 3.5.6

[18:16:15] [Server thread/ERROR]: Could not pass event InventoryClickEvent to PlayerVaults v3.5.6-SNAPSHOT
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.7.jar:git-Spigot-f94fe8f-2642f9b]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.7.jar:git-Spigot-f94fe8f-2642f9b]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.7.jar:git-Spigot-f94fe8f-2642f9b]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.7.jar:git-Spigot-f94fe8f-2642f9b]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1625) [spigot-1.8.7.jar:git-Spigot-f94fe8f-2642f9b]
	at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31) [spigot-1.8.7.jar:git-Spigot-f94fe8f-2642f9b]
	at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9) [spigot-1.8.7.jar:git-Spigot-f94fe8f-2642f9b]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.7.jar:git-Spigot-f94fe8f-2642f9b]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) [spigot-1.8.7.jar:git-Spigot-f94fe8f-2642f9b]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714) [spigot-1.8.7.jar:git-Spigot-f94fe8f-2642f9b]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.7.jar:git-Spigot-f94fe8f-2642f9b]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot-1.8.7.jar:git-Spigot-f94fe8f-2642f9b]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot-1.8.7.jar:git-Spigot-f94fe8f-2642f9b]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.NullPointerException
	at com.drtshock.playervaults.listeners.Listeners.onClick(Listeners.java:247) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor199.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.7.jar:git-Spigot-f94fe8f-2642f9b]
	... 15 more

**Comment by pchard** [comment]
I have a similar problem too:

[02:55:32] [Server thread/ERROR] [Minecraft/]: Could not pass event InventoryClickEvent to PlayerVaults v3.5.7-b${BUILD_NUMBER}
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:git-Cauldron-Reloaded-1.7.10-1.1343.01.0]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:git-Cauldron-Reloaded-1.7.10-1.1343.01.0]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:git-Cauldron-Reloaded-1.7.10-1.1343.01.0]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:git-Cauldron-Reloaded-1.7.10-1.1343.01.0]
        at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:2023) [nh.class:?]
        at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:32) [ix.class:?]
        at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:10) [ix.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:430) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: java.lang.NoSuchMethodError: org.bukkit.event.inventory.InventoryClickEvent.getClickedInventory()Lorg/bukkit/inventory/Inventory;
        at com.drtshock.playervaults.listeners.Listeners.onClick(Listeners.java:121) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor545.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:git-Cauldron-Reloaded-1.7.10-1.1343.01.0]
        ... 13 more

**Comment by drtshock** [comment]
Update bukkit.

**Comment by pchard** [comment]
I can't update it. I'm using cauldron...
26. okt. 2015 5.29 p.m. skrev "Trent Hensler" <notifications@github.com>:

**Comment by pchard** [comment]
I can't. I'm using cauldron.

Closed #98 <https://github.com/drtshock/PlayerVaults/issues/98>.

—
Reply to this email directly or view it on GitHub
<https://github.com/drtshock/PlayerVaults/issues/98#event-445749558>.

**Comment by pchard** [comment]
Also, this is on -every- single PlayerVault versions. I have tried.

**Comment by drtshock** [comment]
Then it's not compatible with cauldron.

**Comment by pchard** [comment]
Weird since it used to work...
4. nov. 2015 6.11 p.m. skrev "Trent Hensler" <notifications@github.com>:

**Comment by KevinNovak** [comment]
This occurs because CraftBukkit does not have the function **getClickedInventory()**. Spigot does have this function.
